### ISSUE TITLE
Behavior of Test-SPDscParameterState is flawed: it should return false if a key in CurrentValues is missing in DesiredValues

### ISSUE THREAD

**Issue by Yvand** [dsccommunity/SharePointDsc#1093]
#### Details of the scenario you tried and the problem that is occurring

I discovered this while writing SPTrustedSecurityTokenIssuer:
Test-SPDscParameterState returns true in the scenario below, while IMO it should return false:

```powershell
Import-Module -Name "C:\Dev\Github\SharePointDsc\Modules\SharePointDsc\Modules\SharePointDsc.Util\SharePointDsc.Util.psm1"

# Very simplified example
$currentValues = @{Ensure="Present"; IsTrustBroker=$true}
$desiredValues = @{Ensure="Present"}

# Test-SPDscParameterState will return $true, while it should return $false
Test-SPDscParameterState -CurrentValues $currentValues `
        -DesiredValues $desiredValues `
        -ValuesToCheck @("Ensure", "IsTrustBroker")
```

Use case: IsTrustBroker is an optional parameter in DSC resource SPTrustedSecurityTokenIssuer.
If it is not in DSC configuration, but it is returned by the Get-TargetResource (in $currentValues), then Test-SPDscParameterState should return false, so that Set-TargetResource function is called to update configuration.
But currently it returns true and Set-TargetResource function is not called.

#### Suggested solution to the issue

Test-SPDscParameterState should return false if a key in CurrentValues is missing in DesiredValues

I suspect that updating Test-SPDscParameterState to change this would impact many resources in the module, and potentially break many.

As a workaround, in SPTrustedSecurityTokenIssuer I do the following:

- Explicitly add IsTrustBroker in Test-TargetResource if it is missing
- Explicitly set IsTrustBroker to false in both Test-TargetResource and Get-TargetResource if it's not true (instead of no value at all)

Workaround in Test-SPDscParameterState, before calling Test-SPDscParameterState:

```powershell
if ($PSBoundParameters.ContainsKey("IsTrustBroker") -eq $false)
{
	$PSBoundParameters.Add("IsTrustBroker", $false)
}
```

#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2019

#### Version and build of PowerShell the target node is running

```
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

dev

**Comment by ykuijs** [comment]
Hi @Yvand I prefer implementing the workaround option you describe, the reason being the fact that we would like to only when the values that have been specified in the DSC config. If a user doesn't specify a parameter, they must have a reason for that: Most probably because they do not care about the value of that parameter, they allow it to be configured outside of DSC. By updating this method, we would seriously break many resources.

If a parameter should have a default value, we should specify that in the resource, for example like we do in the following resource:
https://github.com/PowerShell/SharePointDsc/blob/3cca89623ad4fc6de752028c7b0b799d6dfac99f/Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1#L104-L128

The Version parameter has been configured with a default value and the Test method specifically updates the PSBoundParameter variable, since default values are not included into that variable.

**Comment by andikrueger** [comment]
This is an issue that is common across several DSC resources. IMHO Test should only test required and bound parameters.

Is there any option available to make this test more generic and get rid of the problem of implementing a workaround for each resource?

Pseudo-Code for a helper function to get some information:

```
function Get-BoundAndDefaultParameters
{
    param($BoundParameters)

    return $BoundParameters.Keys + `RequiredParameters used by the resource` + `DefaultParameters set in the method`
}
```

**Comment by ykuijs** [comment]
I believe we need to implement something in each resource. Unfortunately the $PSBoundParameters variable only contains the explicitly specified parameters, not any default value for unspecified parameters. There is [a way](https://www.briantist.com/how-to/splatting-psboundparameters-default-values-optional-parameters/) to create a new variable with both the specified and default parameters, but that needs to be done in each resource.

**Comment by andikrueger** [comment]
@ykuijs good find!

Do I understand it correctly: We would need to do the following steps to fix this issue:
- Go through all resources
- Check for any implementation that's not using $PSBoundParamters for `Test-SPDscParameterState` 
- add every "default value parameter" to `$PSBoundParameters` object

**Comment by ykuijs** [comment]
I believe all resource already have this implemented, else the unit tests couldn't have been created successfully :-)

@Yvand I was just reviewing the SPTrustedSecurityTokenIssuer resource you were referring to. I noticed that the IsTrustBroker parameter has a default value of $true, but the code in the Test method that populates this parameter in PSBoundParameters the value was set to $false. Which one should be the correct one? My guess is $false, am I correct?

**Comment by Yvand** [comment]
[IsTrustBroker ](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-sptrustedsecuritytokenissuer?view=sharepoint-ps) parameter is an optionnal SwitchParameter: you specify it or not, and it does not take any value.
So the answer to your question is arbitrary. My opinion: by default it should be present (so have default value $true in the DSC resource)

**Comment by ykuijs** [comment]
Ok great, but then the code does not work correctly. You also specified the following
```PowerShell
    if ($PSBoundParameters.ContainsKey("IsTrustBroker") -eq $false)
    {
        $PSBoundParameters.Add("IsTrustBroker", $false)
    }
```
So if the IsTrustBroker isn't specified, PS sets it to True as default value. However because default values are not included into the PSBoundParameters variable, you set it to false here. Same is true in the Set method.

I will submit a PR correct the issue
