### ISSUE TITLE
SPSearchTopology FirstIndexPartition Issue for Default folder

### ISSUE THREAD

**Issue by NikCharlebois** [dsccommunity/SharePointDsc#1095]
#### Details of the scenario you tried and the problem that is occurring
Assume we have a Search Farm with 3 servers: ServerA, ServerB and ServerC. ServerB is the one that will be hosting the index. If we run the configuration from ServerA, and in there we have a block similar to the following:
```
$creds = Get-Credential
    Node ServerA
    {
        SPSearchTopology MyTopology
        {
            ServiceAppName          = "Search Service Application"
            Admin                   = @("ServerA")
            Crawler                 = @("ServerC")
            ContentProcessing       = @("ServerA")
            AnalyticsProcessing     = @("ServerA")
            QueryProcessing         = @("ServerA")
            IndexPartition          = @("ServerB")
            FirstPartitionDirectory = "C:\Index"
            PSDscRunAsCredential    = $creds
        }
    }
```

It will throw an error because folder c:\index needs to exist locally, in occurance on ServerA, even though it will never host the partition. This is caused by the following lines in the resource:
```
# Create the directory on the local server as it will not apply the topology without it
if ((Test-Path -Path $params.FirstPartitionDirectory) -eq $false)
{
    New-Item $params.FirstPartitionDirectory -ItemType Directory -Force
}
```
#### Verbose logs showing the problem
Error message that the drive doesn't exist.

#### Suggested solution to the issue
Prevent from having to create the folder locally if current server is not listed in IndexPartition.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
See above

#### The operating system the target node is running
Win Server 2016
SharePointDSC 3.4.0.0

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.4.0.0

**Comment by ykuijs** [comment]
@NikCharlebois I see what you mean here and I agree with your suggestion. Just wondering: Why does this throw an error that the drive doesn't exist in this example?

**Comment by ykuijs** [comment]
And do you have a suggestion on how we can make sure the folder exists on all servers that host the index partition? Or should this be achieved by using the File resource in a config?

**Comment by ykuijs** [comment]
What I did for a customer is just adding the File resource to the config for all servers that are going to run the Index partition. This way you prevent the above issue all together. We can simply add this as best practice to the documentation.

**Comment by ykuijs** [comment]
Did some research on this issue and I believe that this code was added due to the fact there was an issue in SP2013. See [here](https://support.office.com/en-us/article/sharepoint-server-2013-known-issues-780242a6-236e-4d7a-8379-118a1aaa2a51) and search for RootDirectory.

It looks like this issue is resolved in SP2016 and later.

I suggest to change the code for SP2013 to the code mentioned in the article, so we can remove the folder creation code you are getting the issue on.
