### ISSUE TITLE
Add support for SQL Authentication (e.g. for Azure SQL Managed Instance as a back-end)

### ISSUE THREAD

**Issue by brianlala** [dsccommunity/SharePointDsc#1121]
Currently SharePointDSC only supports Windows Integrated authentication (which has worked fine in the overwhelming majority of cases). However, some customers have expressed an interest in leveraging Azure SQL Managed Instance as a back-end database for SharePoint in Azure IaaS. While SQL Managed Instances are supported by the product, they don't currently support Windows Integrated auth as they aren't domain-joined. Therefore, we would need to make some fairly significant updates to SharePointDSC to work with Managed Instances (which use SQL authentication - as well as AAD but AFAIK SharePoint can't use that).

I'll be submitting a PR shortly that seeks to address this shortcoming.

**Comment by ykuijs** [comment]
Implemented in v4.0-dev branch via PR #1156
