### ISSUE TITLE
SPWebAppSuiteBar: Resource not working with SP2019, add notifications to the resource

### ISSUE THREAD

**Issue by aniket25** [dsccommunity/SharePointDsc#1139]
ISSUE TITLE:
    SPWebAppSuiteBar is not working with 2019.

ISSUE DESCRIPTION (this template):
    When I ran this module for SP 201 it is working as expectd but when run on 2019 it is not able to make changes as required.
I look in few forums and it has been confirmed this is not supported in 2019 version as "SharePoint" text is hard coded and even CSS is only able to work on classic pages and not modern pages.

**Comment by ykuijs** [comment]
Hi @aniket25 Do you have the links to the forum posts you are referring to? And do you get any error messages or does the resource work correctly but the change doesn't have any effect on SharePoint?

**Comment by ykuijs** [comment]
@aniket25 Do you have an update for me?

**Comment by ruandersMSFT** [comment]
Yorick,

Here's what I'm seeing on [StackExchange - Edit Suite Bar Links in SharePoint 2019](https://sharepoint.stackexchange.com/questions/255157/edit-suite-bar-links-in-sharepoint-2019):

Possibly related to SuiteNavBrandingText changing from "SharePoint" to another value:  "I have the PowerShell solution and I have been able to change everything except the Name."

Russell

**Comment by jensotto** [comment]
In SharePoint 2019 and SharePoint Online you are not supposed to be able change the text in the Suite Nav. As far as I can tell this is now meant to indicate what application in Office 365 the user is currently using, and changing this to a custom value can be confusing. This is probably why it's no longer supported to change SuiteNavBrandingText as you could for previous versions of SharePoint.
This is not a limitation of SharePointDSC. It's a change internally in SharePoint.

**Comment by ykuijs** [comment]
Checked with a colleague and it is indeed no longer working in SP2019. This means we have to extend the version checks to show warnings when SP2019 is used.

**Comment by jensotto** [comment]
I disagree with this being an issue and that this has been changed. It's not invalid or an error to modify the Suite Bar properties on the web application object for SharePoint 2019. It works perfectly fine if you are using a master page that supports it (for eksample a SharePoint 2013 master page) as I've mentioned before regarding the same functionality. It is not up to SharePointDSC to decide if modifying these properties should throw errors or not. That is entirely up to SharePoint. If SharePoint supports modifying these properties SharePointDSC should too. We can't forsee what will work in different scenarios, and therefore this modification has to be allowed for SharePoint 2019.
I don't think a mainstream usage of SharePoint should dictate what errors SharePointDSC should throw. It is clearly indicated in the wiki that some functionality might not work as expected, but it might probably be made even clearer.
I propose to revert the change made for this issue.
