### ISSUE TITLE
SPProductUpdate: Not installing SharePoint 2013 SP1

### ISSUE THREAD

**Issue by bminisi** [dsccommunity/SharePointDsc#1159]
Adding SPProductUpdate after install binaries, CU and creating the farm, SPProductUpdate is being used to install SP1.  It shows in the DSC log that it succeeded, but it never actually gets installed.  SPConfigWizard is run after the SP1 resource.  SP1 is the normal .exe install file.  The Upgrade Status page does not even show that it was attempted.

The below resource runs in 2 minutes.  Running SP1 manually takes 30 minutes.

SPProductUpdate InstallSP1
        {
            SetupFile            = $Sp1Path
            ShutdownServices     = $true
            Ensure               = "Present"
            PsDscRunAsCredential = $SPInstallCred

            DependsOn            = '[SPFarm]SharePointFarm'
        }

Log:
[SPFarmAdministrators]LocalFarmAdmins] Farm Administrators group matches"},
  {"time": "blaT14:33:01.827+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Test     ]  [[SPFarmAdministrators]LocalFarmAdmins]  in 0.2680 seconds."},
  {"time": "blaT14:33:01.827+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Skip   Set      ]  [[SPFarmAdministrators]LocalFarmAdmins]  "},
  {"time": "blaT14:33:01.827+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Resource ]  [[SPFarmAdministrators]LocalFarmAdmins]  "},
  {"time": "blaT14:33:01.827+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Start  Resource ]  [[xCredSSP]CredSSPServer]  "},
  {"time": "blaT14:33:01.827+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Start  Test     ]  [[xCredSSP]CredSSPServer]  "},
  {"time": "blaT14:33:01.874+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Test     ]  [[xCredSSP]CredSSPServer]  in 0.0470 seconds."},
  {"time": "blaT14:33:01.874+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Skip   Set      ]  [[xCredSSP]CredSSPServer]  "},
  {"time": "blaT14:33:01.874+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Resource ]  [[xCredSSP]CredSSPServer]  "},
  {"time": "blaT14:33:01.874+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Start  Resource ]  [[xCredSSP]CredSSPClient]  "},
  {"time": "blaT14:33:01.874+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Start  Test     ]  [[xCredSSP]CredSSPClient]  "},
  {"time": "blaT14:33:01.913+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Test     ]  [[xCredSSP]CredSSPClient]  in 0.0390 seconds."},
  {"time": "blaT14:33:01.913+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Skip   Set      ]  [[xCredSSP]CredSSPClient]  "},
  {"time": "blaT14:33:01.913+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Resource ]  [[xCredSSP]CredSSPClient]  "},
  {"time": "blaT14:33:01.913+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Start  Resource ]  [[SPProductUpdate]InstallServicePack1]  "},
  {"time": "blaT14:33:01.913+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Start  Test     ]  [[SPProductUpdate]InstallServicePack1]  "},
  {"time": "blaT14:33:02.171+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Testing install status of SP Update binaries"},
  {"time": "blaT14:33:02.171+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Getting install status of SP binaries"},
  {"time": "blaT14:33:02.171+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Checking file status of C://Install//SP2013SP1//officeserversp2013-kb2880552-fullfile-x64-en-us.exe"},
  {"time": "blaT14:33:02.171+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Update has version 15.0.4571.1502"},
  {"time": "blaT14:33:02.171+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Executing as the local run as user MyDomain\\AdminDomainAccount"},
  {"time": "blaT14:33:02.171+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving BeginProcessing Method of Get-SPFarm."},
  {"time": "blaT14:33:02.171+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving ProcessRecord Method of Get-SPFarm."},
  {"time": "blaT14:33:02.172+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving EndProcessing Method of Get-SPFarm."},
  {"time": "blaT14:33:02.172+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving BeginProcessing Method of Get-SPServer."},
  {"time": "blaT14:33:02.173+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving ProcessRecord Method of Get-SPServer."},
  {"time": "blaT14:33:02.173+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving EndProcessing Method of Get-SPServer."},
  {"time": "blaT14:33:02.173+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Update is a Service Pack for SharePoint."},
  {"time": "blaT14:33:02.173+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Executing as the local run as user MyDomain\\AdminDomainAccount"},
  {"time": "blaT14:33:02.173+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving BeginProcessing Method of Get-SPFarm."},
  {"time": "blaT14:33:02.173+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving ProcessRecord Method of Get-SPFarm."},
  {"time": "blaT14:33:02.174+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving EndProcessing Method of Get-SPFarm."},
  {"time": "blaT14:33:02.174+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving BeginProcessing Method of Get-SPServer."},
  {"time": "blaT14:33:02.174+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving ProcessRecord Method of Get-SPServer."},
  {"time": "blaT14:33:02.174+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] Leaving EndProcessing Method of Get-SPServer."},
  {"time": "blaT14:33:02.175+01:00", "type": "verbose", "message": "[bla]:                            [[SPProductUpdate]InstallServicePack1] The lowest version of any SharePoint component is 15.0.4763.1000"},
  {"time": "blaT14:33:02.184+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Test     ]  [[SPProductUpdate]InstallServicePack1]  in 0.2710 seconds."},
  {"time": "blaT14:33:02.184+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Skip   Set      ]  [[SPProductUpdate]InstallServicePack1]  "},
  {"time": "blaT14:33:02.185+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Resource ]  [[SPProductUpdate]InstallServicePack1]  "},
  {"time": "blaT14:33:02.185+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Start  Resource ]  [[SPConfigWizard]RunConfigWizardB]  "},
  {"time": "blaT14:33:02.185+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Start  Test     ]  [[SPConfigWizard]RunConfigWizardB]  "},
  {"time": "blaT14:33:02.339+01:00", "type": "verbose", "message": "[bla]:                            [[SPConfigWizard]RunConfigWizardB] Testing status of Configuration Wizard"},
 {"time": "blaT14:33:02.339+01:00", "type": "verbose", "message": "[bla]:                            [[SPConfigWizard]RunConfigWizardB] Getting status of Configuration Wizard"},
  {"time": "blaT14:33:02.347+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Test     ]  [[SPConfigWizard]RunConfigWizardB]  in 0.1620 seconds."},
  {"time": "blaT14:33:02.347+01:00", "type": "verbose", "message": "[bla]: LCM:  [ Skip   Set      ]  [[SPConfigWizard]RunConfigWizardB]  "},
  {"time": "blaT14:33:02.347+01:00", "type": "verbose", "message": "[bla]: LCM:  [ End    Resource ]  [[SPConfigWizard]RunConfigWizardB]  "},

OsName               : Microsoft Windows Server 2012 R2 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19478.amd64fre.winblue_ltsb.190831-0600
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

SharePoint 2013 - CUOct2015 update

PS: 5.1

DSC Version: 2.4

**Comment by ykuijs** [comment]
Hi @bminisi, there has been a major refactor of this resource in v3.x. Could you please update to v3.7 (the most recent version) and try again? My guess is that this will work much better.

**Comment by ykuijs** [comment]
This update was in v3.3: https://techcommunity.microsoft.com/t5/sharepointdsc/new-release-a-new-month-time-for-sharepointdsc-v3-3/ba-p/393586

**Comment by bminisi** [comment]
Hi @ykuijs we upgraded to 3.7 and seems to be working now.  Thanks for the suggestion.

**Comment by ykuijs** [comment]
Closing issue
