### ISSUE TITLE
MSFT_SPUserProfileProperty - Added property, fixed bug

### ISSUE THREAD

**Issue by ThomasLie** [dsccommunity/SharePointDsc#1164]
Hi there,

found a bug in MSFT_SPUserProfileProperty.psm1 (module version 3.7.0.0), line 891:

`return Test-SPDscParameterState -CurrentValues $CurrentValues `
            -DesiredValues $PSBoundParameters `
            -ValuesToCheck @("Name",
            "DisplayName",
            "Type",
            "Description",
            "PolicySetting",
            "PrivacySetting",
            "PropertyMappings",
            "Length",
            "DisplayOrder",
            "IsEventLog",
            "IsVisibleOnEditor",
            "IsVisibleOnViewer",
            "IsUserEditable",
            "IsAlias",
            "IsSearchabe",
            "UserOverridePrivacy",
            "TermGroup",
            "TermStore",
            "TermSet",
            "Ensure")`

String 'IsSearchabe' should be 'IsSearchable'

Furthermore, I suggest to add ability to set the property 'isReplicable', proposed solution is attached.

Thanks...
[MSFT_SPUserProfileProperty.zip](https://github.com/dsccommunity/SharePointDsc/files/4185149/MSFT_SPUserProfileProperty.zip)

**Comment by ykuijs** [comment]
Good spot and great addition. Would it be possible to submit a PR with these changes?

**Comment by ruandersMSFT** [comment]
@ykuijs I have the changes in progress and will have in a PR today.

**Comment by ruandersMSFT** [comment]
Testing demonstrates _IsReplicable_ not found via _CoreProperty_ or _TypeProperty_ : 
![image](https://user-images.githubusercontent.com/16927960/74792955-221d7680-527c-11ea-8efe-6cbc84b9621c.png)

Also need to review consideration of Replicable setting only available when _Default Privacy Setting_ is changed from _Only Me_ to _Everyone_:

![image](https://user-images.githubusercontent.com/16927960/74793055-76c0f180-527c-11ea-9cd7-938c6b470930.png)

**Comment by ThomasLie** [comment]
Hi guys,

as per Microsoft  the property can be set:

public bool IsReplicable { get; set; }

https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.server.userprofiles.profiletypeproperty.isreplicable?view=sharepoint-server

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT Consulting & Büroservices GbR
Ilse-Pohl-Strasse 67
63303 Dreieich - Germany

Fon: +49 171.2625166
Email: thomas@lieftuechter.de<mailto:thomas@lieftuechter.de>
Web:  http://www.lieftüchter.de/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: ruandersMSFT <notifications@github.com>
Gesendet: Mittwoch, 19. Februar 2020 02:31
An: dsccommunity/SharePointDsc <SharePointDsc@noreply.github.com>
Cc: Thomas Lieftüchter <thomas@lieftuechter.de>; Author <author@noreply.github.com>
Betreff: Re: [dsccommunity/SharePointDsc] MSFT_SPUserProfileProperty - Added property, fixed bug (#1164)


Testing demonstrates IsReplicable not found via CoreProperty or TypeProperty :
[image]<https://user-images.githubusercontent.com/16927960/74792955-221d7680-527c-11ea-8efe-6cbc84b9621c.png>

Also need to review consideration of Replicable setting only available when Default Privacy Setting is changed from Only Me to Everyone:

[image]<https://user-images.githubusercontent.com/16927960/74793055-76c0f180-527c-11ea-9cd7-938c6b470930.png>
