### ISSUE TITLE
SPUserProfileSyncService - FarmAccount

### ISSUE THREAD

**Issue by ruandersMSFT** [dsccommunity/SharePointDsc#1165]
The FarmAccount parameter of [SPUserProfileSyncService ](https://github.com/dsccommunity/SharePointDsc/wiki/SPUserProfileSyncService)is documented as "PARAMETER IS NOT USED ANYMORE, WILL BE REMOVED IN V3.0"; however, the parameter still exists.  Recommend completing parameter removal for v4.0 release.

**Comment by ruandersMSFT** [comment]
![image](https://user-images.githubusercontent.com/16927960/74685027-911aa280-518a-11ea-9410-205666157121.png)

**Comment by ruandersMSFT** [comment]
![image](https://user-images.githubusercontent.com/16927960/74685048-a099eb80-518a-11ea-8927-476035b92038.png)

**Comment by ykuijs** [comment]
Closed via PR #1170
