### ISSUE TITLE
SPFarmSolution: 'Cannot find error' thrown when 'Absent'

### ISSUE THREAD

**Issue by ruandersMSFT** [dsccommunity/SharePointDsc#1179]
#### Details of the scenario you tried and the problem that is occurring

Running SPFarmSolution with Ensure = 'Absent' against a solution that does in fact not exist throws an exception that the solution could not be found.  It should not throw this exception when it does not exist, and the resource is set to Absent, as a Solution that does not exist and configured to be Absent is correct state.

#### Verbose logs showing the problem

VERBOSE: [localhost]:[SP201902]: LCM:  [ Start  Set      ]  [[SPFarmSolution]FarmSolution_LDAPCP.wsp::[SharePointServerFarmConfiguration]DeployFarmConfig]
VERBOSE: [localhost]:[SP201902]:                            [[SPFarmSolution]FarmSolution_LDAPCP.wsp::[SharePointServerFarmConfiguration]DeployFarmConfig] Setti
ng farm solution 'LDAPCP.wsp' settings
VERBOSE: [localhost]:[SP201902]:                            [[SPFarmSolution]FarmSolution_LDAPCP.wsp::[SharePointServerFarmConfiguration]DeployFarmConfig] Getti
ng farm solution 'LDAPCP.wsp' settings
VERBOSE: [localhost]:[SP201902]:                            [[SPFarmSolution]FarmSolution_LDAPCP.wsp::[SharePointServerFarmConfiguration]DeployFarmConfig] Execu
ting as the local run as user RA\svc.dev.spexec
VERBOSE: [localhost]:[SP201902]:                            [[SPFarmSolution]FarmSolution_LDAPCP.wsp::[SharePointServerFarmConfiguration]DeployFarmConfig] Execu
ting as the local run as user RA\svc.dev.spexec
Cannot find an SPSolution object with Id or Name: LDAPCP.wsp.
    + CategoryInfo          : InvalidData: (Microsoft.Share...dletGetSolution:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletGetSolution
    + PSComputerName        : [localhost]

![image](https://user-images.githubusercontent.com/16927960/75728638-b38ddf00-5ca5-11ea-82fb-ead6e2466714.png)

#### Suggested solution to the issue

Code update / do not throw error when missing and Absent.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
SPFarmSolution SampleWsp
            {
                Name                 = "ThisDoesntExist.wsp"
                LiteralPath          = "C:\src\ThisDoesntExist.wsp"
                Ensure               = "Absent"
                Version              = "1.0.0"
                WebAppUrls           = @("http://collaboration", "http://mysites")
                PsDscRunAsCredential = $SetupAccount
            }
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2019

#### Version and build of PowerShell the target node is running

Name                           Value                                                                                                                           
----                           -----                                                                                                                           
PSVersion                      5.1.18362.628                                                                                                                   
PSEdition                      Desktop                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                         
BuildVersion                   10.0.18362.628                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                 
WSManStackVersion              3.0                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                             
SerializationVersion           1.1.0.1  

#### Version of the DSC module that was used

3.8.0

**Comment by ruandersMSFT** [comment]
Further testing has identified two bugs in near proximity towards the end of Set-TargetResource:

Bug 1)  The call to Wait-SPDscSolutionJob fails because the solution does not exist.  We should only be waiting for a Solution Job for an Ensure = 'Present' solution.

Bug 2)  The code for Remove-SPSolution is executed for a solution that is already known to be absent, thus throwing an error that the Solution cannot be found.  The code should check if the $CurrentValues.Ensure is already known to be Absent and not attempt to remove a solution that is known to not exist.

**Comment by ruandersMSFT** [comment]
Successful run with Farm Solution 'Absent' verified by code changes:

![image](https://user-images.githubusercontent.com/16927960/75791490-deba1200-5d29-11ea-9932-5879aeb2a665.png)

**Comment by ykuijs** [comment]
In the future: Please leave the issue open when submitting the PR. Merging the PR will automatically close the issue ;-)
