### ISSUE TITLE
DSC SPFarm module error

### ISSUE THREAD

**Issue by nikhillotia** [dsccommunity/SharePointDsc#1191]
Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
    Getting an error when running DSC Sharepoint farm
    'SharePoint DSC: Credential prompt not accepting credentials and passpharise prompting to enter user name and password. 

    ISSUE DESCRIPTION (this template):
    Please provide information regarding your issue under each header below.
    Write N/A under any headers that do not apply to your issue, or if the
    information is not available.

    NOTE! Sensitive information should be obfuscated.

    PLEASE KEEP THE HEADERS.

#### Verbose logs showing the problem
ConvertTo-MOFInstance : System.InvalidOperationException error processing property 'PsDscRunAsCredential' OF TYPE
'SPFarm': Converting and storing encrypted passwords as plain text is not recommended. For more information on
securing credentials in MOF file, please refer to MSDN blog: http://go.microsoft.com/fwlink/?LinkId=393729
At E:\Scripts\spfarm.ps1:20 char:13
+   SPFarm
At line:341 char:16
+     $aliasId = ConvertTo-MOFInstance $keywordName $canonicalizedValue
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessProperty,ConvertTo-MOFInstance
Compilation errors occurred while processing configuration 'SPFarm'. Please review the errors reported in error stream
and modify your configuration code appropriately.
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917
char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SPFarm:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# insert configuration here
Configuration SPFarm
    {
	
        param(
            [Parameter(Mandatory = $true)]
            [PSCredential]
            $FarmAccount,

            [Parameter(Mandatory = $true)]
            [PSCredential]
            $SetupAccount,

            [Parameter(Mandatory = $true)]
            [PSCredential]
            $Passphrase
        )
        Import-DscResource -ModuleName SharePointDsc

        node localhost {
            SPFarm SharePointFarm
            {
                IsSingleInstance          = "Yes"
                DatabaseServer            = "SQL.contoso.local\SQLINSTANCE"
                FarmConfigDatabaseName    = "SP_Config"
                AdminContentDatabaseName  = "SP_AdminContent"
                ServerRole                = "ApplicationWithSearch"
                Passphrase                = $Passphrase
                FarmAccount               = $FarmAccount
                RunCentralAdmin           = $true
                PsDscRunAsCredential      = $SetupAccount
			
            }
        }
    }
    SPFarm 

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.0.amd64fre.rs1_release.160715-1616
OsLanguage           : en-US
OsMuiLanguages       : {en-US}



#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used
SharePoint DSC 3.8.0

**Comment by ykuijs** [comment]
Hi @nikhillotia 

When you are using resources that require credentials, you need to do one of two things:

1. Secure the MOF file by creating a encryption certificate, as described [here](https://docs.microsoft.com/en-us/powershell/scripting/dsc/pull-server/securemof?view=powershell-7)
   - **Recommended** method
   - Will **encrypt** the used passwords in the MOF file.
   - Requires a little work to setup.

1. Specify that plain text passwords are allowed, as described [here](https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/configdatacredentials?view=powershell-7)
   - **NOT recommended** for production use
   - Will store the used passwords in **plain text** into the MOF file
   - Quick to configure, but insecure.
   - Mainly for development purposes

**Comment by nikhillotia** [comment]
thank you for the response Yorick.  I added below two lines in configuration but now getting error.

PSDscAllowPlainTextPassword = $true
PSDscAllowDomainUser 	= $true

At E:\Scripts\spfarm.ps1:30 char:3
+         PSDscAllowPlainTextPassword = $true
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
The member 'PSDscAllowPlainTextPassword' is not valid. Valid members are
'AdminContentDatabaseName', 'ApplicationCredentialKey', 'CentralAdministrationAuth', 'CentralAdministrationPort',
'CentralAdministrationUrl', 'DatabaseServer', 'DependsOn', 'DeveloperDashboard', 'Ensure', 'FarmAccount',
'FarmConfigDatabaseName', 'InstallAccount', 'IsSingleInstance', 'Passphrase', 'PsDscRunAsCredential',
'RunCentralAdmin', 'ServerRole'.
At E:\Scripts\spfarm.ps1:31 char:3
+         PSDscAllowDomainUser     = $true
+         ~~~~~~~~~~~~~~~~~~~~
The member 'PSDscAllowDomainUser' is not valid. Valid members are
'AdminContentDatabaseName', 'ApplicationCredentialKey', 'CentralAdministrationAuth', 'CentralAdministrationPort',
'CentralAdministrationUrl', 'DatabaseServer', 'DependsOn', 'DeveloperDashboard', 'Ensure', 'FarmAccount',
'FarmConfigDatabaseName', 'InstallAccount', 'IsSingleInstance', 'Passphrase', 'PsDscRunAsCredential',
'RunCentralAdmin', 'ServerRole'.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidInstanceProperty

**Comment by ykuijs** [comment]
You should be using a ConfigurationData variable for this. For example:

```PowerShell
Configuration SPFarm
{
    param
    (
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $FarmAccount,

        [Parameter(Mandatory = $true)]
        [PSCredential]
        $SetupAccount,

        [Parameter(Mandatory = $true)]
        [PSCredential]
        $Passphrase
    )

    Import-DscResource -ModuleName SharePointDsc

    node localhost
    {
        SPFarm SharePointFarm
        {
            IsSingleInstance          = "Yes"
            DatabaseServer            = "SQL.contoso.local\SQLINSTANCE"
            FarmConfigDatabaseName    = "SP_Config"
            AdminContentDatabaseName  = "SP_AdminContent"
            ServerRole                = "ApplicationWithSearch"
            Passphrase                = $Passphrase
            FarmAccount               = $FarmAccount
            RunCentralAdmin           = $true
            PsDscRunAsCredential      = $SetupAccount
			
        }
    }
}

$cd = @{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            PSDscAllowDomainUser = $true
            PSDscAllowPlainTextPassword = $true
        }
    )
}

SPFarm -ConfigurationData $cd -FarmAccount $farm -SetupAccount $setup -Passphrase $passphrase
```

**Comment by nikhillotia** [comment]
this worked! Appreciate all your help.

**Comment by ykuijs** [comment]
You are welcome!
