### ISSUE TITLE
SPConfigWizard | The term 'Get-SPFarm' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by philippe-entringer** [dsccommunity/SharePointDsc#1193]
#1180 ## Details of the scenario you tried and the problem that is occurring
The SPConfigWizard calls the Get-SPDscServerPatchStatus Util method which cause the error.

#### Verbose logs showing the problem
`
VERBOSE: [CONTENTFARM]:                            [[SPConfigWizard]APPLICATION_PSConfig_Master]
Setting status of Configuration Wizard
The term "Get-SPFarm" is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
    CategoryInfo          : ObjectNotFound: (Get-SPFarm:) [], CimException
    FullyQualifiedErrorId : CommandNotFoundException
    PSComputerName        : ContentFarm`

#### Suggested solution to the issue
I had to import SharePoint module at the beginning of the function.
`
function Get-SPDscServerPatchStatus
{
    if ((Get-PSSnapin "Microsoft.SharePoint.PowerShell" -ErrorAction SilentlyContinue) -eq $null) 
    {
        write-host "importing SharePoint"
        Add-PSSnapin "Microsoft.SharePoint.PowerShell"
    }
}
`

#### The operating system the target node is running

>OsName               : Microsoft Windows Server 2016 Datacenter 
>OsOperatingSystemSKU : DatacenterServerEdition 
> OsArchitecture       : 64-bit
> WindowsBuildLabEx    : 14393.3659.amd64fre.rs1_release_1.200410-1813
> OsLanguage           : en-US
> OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013 SP1 + CU March 2019

#### Version and build of PowerShell the target node is running
4.0.0

#### Version of the DSC module that was used
SPConfigWizard

**Comment by ykuijs** [comment]
Hi @philippe-entringer, thanks for reporting this issue. I just reviewed the code and see what is going on here. I will fix the issue and submit a new Bugfix PR.
