### ISSUE TITLE
SPConfigWizard | launch Get-SPProduct -local to refresh the Config Database

### ISSUE THREAD

**Issue by philippe-entringer** [dsccommunity/SharePointDsc#1195]
#
![patch status](https://user-images.githubusercontent.com/12797998/80611577-0f24e080-8a3b-11ea-9880-004f74b7dfa6.png)
## Details of the scenario you tried and the problem that is occurring
When Patchin the farm with SPConfigWizard, one of my server is giving "Missing Required" int the Manage Patch Status. I had to manually launch the command "Get-SPProduct -local" to refresh the configuration cache.

#### Suggested solution to the issue
In the Set-TargetResource, Before launching the configuration Wizard, launch 
`Get-SPProduct -local`

#### The operating system the target node is running
> OsName : Microsoft Windows Server 2016 Datacenter
> OsOperatingSystemSKU : DatacenterServerEdition
> OsArchitecture : 64-bit
> WindowsBuildLabEx : 14393.3659.amd64fre.rs1_release_1.200410-1813
> OsLanguage : en-US
> OsMuiLanguages : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013 SP1 + CU March 2019

#### Version and build of PowerShell the target node is running
> PSVersion                      5.1.14409.1018
> PSEdition                      Desktop
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> BuildVersion                   10.0.14409.1018
> CLRVersion                     4.0.30319.42000
> WSManStackVersion              3.0
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1

#### Version of the DSC module that was used
V4.0.0

**Comment by philippe-entringer** [comment]
After multiple test to install CU in Pull mode, after the binaries installation, one of my server 

> WARNING: Upgrade not possible, not all servers have the same binaries installed. Skipping Config Wizard!

I fixed this issue with the following code in **MSFT_SPConfigWizard.psm1**
`        if ($statusType -ne "UpgradeRequired" -and $statusType -ne "UpgradeAvailable")
        {
            Write-Verbose -Message ("WARNING: Upgrade not possible, not all servers have the " + `
                    "same binaries installed. Skipping Config Wizard!")

            Write-Verbose -Message ("Executing Get-SPProduct -local")

            Invoke-SPDscCommand -Credential $InstallAccount `
                -Arguments $PSBoundParameters `
                -ScriptBlock {
                return Get-SPProduct -local
            }
            return
        }
`

**Comment by ykuijs** [comment]
This fix unfortunately won't be possible because this will only work on the local server.

When this resource runs on any other server1, but server2 is reporting the missing upgrade the upgrade won't be possible as well. But but running this command on server1 won't fix the issue either because server2 needs it.

The result of this cmdlet should also be accomplished by the "Product Version Job" timer job, which runs daily around midnight. Could you please test if running that job manually also fixes the issue? Then we can implement initiating that timer job.

**Comment by ykuijs** [comment]
@philippe-entringer Do you have an update?

**Comment by ykuijs** [comment]
You can start the timer job on all servers by using the following command:
```PowerShell
Get-SPTimerJob -Identity job-admin-product-version | Start-SPTimerJob
```

**Comment by philippe-entringer** [comment]
It worked with the command 
Thanks Yorick.

**Comment by ykuijs** [comment]
Will be included in my next Bugfix PR
