### ISSUE TITLE
SPServiceInstance does not wait for service to fully start

### ISSUE THREAD

**Issue by pessimism** [dsccommunity/SharePointDsc#1200]
#### Details of the scenario you tried and the problem that is occurring
-Set a new or slow-loading service instance to Ensure="Present"
-Perform an operation dependent on the service
-The dependent operation can fail causing the DSC run to fail due to the service being in "Provisioning" state and not fully started

#### Verbose logs showing the problem
...
App Management Service           **Provi...** 1f841991-e024-4aec-8ca6-704902e3036e
...
Settings or services required to complete this request are not currently available.  Try this operation again later.
#### Suggested solution to the issue
Poll service instance status and do not return until service state is Online or a timeout elapses
#### The operating system the target node is running
Windows Server 2016

#### Version of SharePoint that is used (e.g. SharePoint 2016)
2019
#### Version and build of PowerShell the target node is running
5.1
#### Version of the DSC module that was used
3.7.0.0

**Comment by ykuijs** [comment]
Great point, recently assisted a customer with troubleshooting an issue that was caused by this exact same problem. Will add some code to wait for the service to start.
