### ISSUE TITLE
Question: Dropping PowerShell v4 support?

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/SharePointDsc#1207]
Currently SharePointDsc includes support for PowerShell v4, which means each resource contains an InstallAccount parameter and some code to elevate the System session to this account. The downside of this method is the requirement of CredSSP for all resources.

PowerShell v5 introduced the PsDscRunAsCredential which natively configures the LCM to use a different account. This method doesn't require CredSSP, is much faster and has better logging.

The question now is: Who out there is still use PowerShell v4?? What are your reasons for not upgrading to PowerShell v5?

**NOTE:** Dropping the PSv4 support unfortunately does not mean we can fully drop the CredSSP requirement. There are still three resources (SPAppCatalog, SPUserProfileServiceApp and SPUserProfileSyncService) that require running as the Farm account and we need CredSSP in order to do that successfully.

**Comment by andikrueger** [comment]
I tend to remove the support for PowerShell v4. All combinations of Windows Server and SharePoint Server can be updated to PowerShell 5.1 or do come with PowerShell 5.1 installed.

This change could impact SharePoint 2013 and 2016 customers with old OS. For SharePoint 2019 it will not be of any impact.

SharePoint Version | Windows OS | PowerShell | WMF 5.1
----|----|----|----
2013|2008 R2 SP1|4|x
2013|2012|4|x
2013|2012 R2|4|x
2016|2012 R2|4|x 
2016|2016|5.1|-
2019|2016|5.1|-
2019|2019|5.1|-

As this change will be a breaking change, we can also consider time as a good a factor. Many products and combinations are running out of support in 2023..

Product|Extended Support End Date
----|----
SharePoint Server 2013 SP1|4/11/2023
SharePoint Server 2016|7/14/2026
SharePoint Server 2019|7/14/2026
Windows Server 2008 R2 SP1|1/14/2020
Windows Server 2012|10/10/2023
Windows Server 2012 R2|10/10/2023
Windows Server 2016|1/12/2027
Windows Server 2019|1/9/2029

Sources:
- https://docs.microsoft.com/de-de/powershell/scripting/install/windows-powershell-system-requirements
- https://support.microsoft.com/en-us/lifecycle/search

**Comment by ykuijs** [comment]
@andikrueger It being a breaking change is the reason I bring it up early. We just released v4.0, which included a few breaking changes. I think 2023 is a little too far in the future, but it will be months before v5.0 will be released. So we are well in time to have this discussion ;-)

I agree with you. Most issues that are filed here are mentioning the use of PS5.1 anyways, but potentially some companies are still using PS4 for whatever reason. So I am interested who might be and what the reasons would be for not upgrading.....

**Comment by brianlala** [comment]
It's easy to simply make v5.1 a requirement since any machine currently running 4 can easily be upgraded, hence I see no reason not to drop support for v4 ASAP.

**Comment by ykuijs** [comment]
Totally agree, but there can be specific reasons companies cannot upgrade to PowerShell v5 we might be overlooking. Technical or otherwise 😉

**Comment by adruet29** [comment]
I agree too, in all our farms it is not an issue to upgrade to 5.1 (most of them already are), so I do not see any reason not to drop v4 support for my environment.

**Comment by ykuijs** [comment]
Closed via PR #1354
