### ISSUE TITLE
Disabling feature returns error if feature already disabled

### ISSUE THREAD

**Issue by VerdonTrigance** [dsccommunity/SharePointDsc#1209]
ISSUE TITLE:
    MSFT_SPFeature.psm1: Disabling feature returns error if feature already disabled

    ISSUE DESCRIPTION (this template):

    PLEASE KEEP THE HEADERS.

MSFT_SPFeature.psm1: Disabling feature returns error if feature already disabled.

Guys, you again broke main DSC rule - idempotent! If you deactivate feature that already has been deactivated you getting the error. This is nonsense! 

    Set-Feature -Name "Project_MyFarmFeature" -Url $(webapplication) -FeatureScope Farm -Ensure Absent

where Set-Feature is just renamed Set-TargetResource called explicitly

#### Verbose logs showing the problem

```
VERBOSE: Executing as the local run as user CORP\dev_user
VERBOSE: Leaving BeginProcessing Method of Get-SPFeature.
VERBOSE: Leaving ProcessRecord Method of Get-SPFeature.
VERBOSE: Leaving EndProcessing Method of Get-SPFeature.
VERBOSE: Executing as the local run as user CORP\dev_user
VERBOSE: Disable Feature 'Project_MyFarmFeature' because 
'Ensure' is 'Absent'...
VERBOSE: Leaving BeginProcessing Method of Disable-SPFeature.
VERBOSE: Leaving ProcessRecord Method of Disable-SPFeature.
Disable-SPFeature : Feature 'f65b3b80-70d3-43ef-905f-2bf08870b84a' is not activ
ated at this scope.
At line:22 char:13
+             Disable-SPFeature @runParams
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...tDisableFeature: 
   SPCmdletDisableFeature) [Disable-SPFeature], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletDisableF 
   eature
```

#### Suggested solution to the issue

Check $CurrentValues before call Disable-SPFeature @runParams

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
Set-Feature -Name "Project_MyFarmFeature" -Url $(webapplication) -FeatureScope Farm -Ensure Absent
```

where Set-Feature is just renamed Set-TargetResource called explicitly

#### Version of SharePoint that is used (e.g. SharePoint 2016)

Sharepoint 2013

#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ykuijs** [comment]
Hi @VerdonTrigance Can you provide a little more logging? Preferable the logging of the Test just before the LCM tries to apply the desired state.

If the feature is already disabled, the Set method shouldn't be called unless the version parameter isn't in the desired state. Those are the two parameters we check on.

**Comment by VerdonTrigance** [comment]
> Hi @VerdonTrigance Can you provide a little more logging? Preferable the logging of the Test just before the LCM tries to apply the desired state.
> 
> If the feature is already disabled, the Set method shouldn't be called unless the version parameter isn't in the desired state. Those are the two parameters we check on.

Khm. I forgot about it, because calling it explicitly. Sorry for that, I will check Test method later.
