### ISSUE TITLE
[SPOutgoingEmailSettings] Only the first eight characters of a custom log name are significant, and there is already another log on the system using the  first eight characters of the name given. Name given: 'SharePointDsc', name of existing log: 'SharePoint Event Log'.

### ISSUE THREAD

**Issue by ChristophHannappel** [dsccommunity/SharePointDsc#1214]
#### Details of the scenario you tried and the problem that is occurring
Trying to configure the Outgoing Email Settings in SharePoint Server 2013. When applying the configuration DSC is not happy about another Eventlog which also Starts with "SharePoint".
According to the error messages the uniqueness of a Eventlog Name is just checked on the first eight characters.

#### Verbose logs showing the problem
```
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Getting outgoing email set
tings configuration for http://SPServer:55000
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Getting outgoing email set
tings configuration for http://SPServer:55000
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Executing as the local run
 as user DOMAIN\DSCAccount
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Leaving BeginProcessing Me
thod of Get-SPWebApplication.
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Leaving ProcessRecord Meth
od of Get-SPWebApplication.
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Leaving EndProcessing Meth
od of Get-SPWebApplication.
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Current Values: CharacterS
et=65001; FromAddress=sharepoint-test2013@domain.de; ReplyToAddress=sharepoint-test2013@domain.de; SMTPPort=; SMTPServer=OldSmtpServer.domain.tld; UseTLS=; WebAppUrl=http://SPServer:55000/
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Target Values: CharacterSe
t=65001; FromAddress=Sharepoint-Test2013@domain.de; ReplyToAddress=Sharepoint-Test2013@domain.de; SMTPServer=NewSmtpServer.domain.tld; Verbose=True; WebAppUrl=http://SPServer:55000
Only the first eight characters of a custom log name are significant, and there is already another log on the system using the 
first eight characters of the name given. Name given: 'SharePointDsc', name of existing log: 'SharePoint Event Log'.
    + CategoryInfo          : InvalidArgument: (:) [], CimException
    + FullyQualifiedErrorId : NewEventlogException,Microsoft.PowerShell.Commands.NewEventLogCommand
    + PSComputerName        : SPServer.DOMAIN.de
 
The source name "MSFT_SPOutgoingEmailSettings" does not exist on computer "localhost".
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteEventLogCommand
    + PSComputerName        : SPServer.DOMAIN.de
 
VERBOSE: [SPServer]:                            [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm] Test-TargetResource return
ed False
VERBOSE: [SPServer]: LCM:  [ End    Test     ]  [[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm]  in 7.9060 seconds.
The PowerShell DSC resource '[SPOutgoingEmailSettings]OutgoingEMailSettings-Farm' with SourceInfo 
'e:\PowerShell DSC\Configuration\SharePointServer2013-SPE15.ps1::217::9::SPOutgoingEmailSettings' threw one or more non-terminating errors 
while running the Test-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : SPServer.DOMAIN.de
```
#### Suggested solution to the issue
Maybe a more unique EventLog Name to prevent a collision with an existing Log File.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
 SPOutgoingEmailSettings OutgoingEMailSettings-Farm
        {
            DependsOn = $null
            PsDscRunAsCredential = $DSCAccount
            WebAppUrl = $ConfigurationData.nonNodeData.CAUrl
            SMTPServer = $ConfigurationData.nonNodeData.SMTPRelay
            FromAddress = $ConfigurationData.nonNodeData.FromAddress
            ReplyToAddress = $ConfigurationData.nonNodeData.FromAddress
            CharacterSet = '65001' # UTF-8
        }
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2012 R2 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19697.amd64fre.winblue_ltsb.200411-0600
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint Server 2013
#### Version and build of PowerShell the target node is running

Name                           Value                                                                                             
----                           -----                                                                                             
PSVersion                      5.1.14409.1018                                                                                    
PSEdition                      Desktop                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                           
BuildVersion                   10.0.14409.1018                                                                                   
CLRVersion                     4.0.30319.42000                                                                                   
WSManStackVersion              3.0                                                                                               
PSRemotingProtocolVersion      2.3                                                                                               
SerializationVersion           1.1.0.1 

#### Version of the DSC module that was used
4.1.0

**Comment by ykuijs** [comment]
Hi @ChristophHannappel, thanks for reporting this. Apparently I did not have any logs named "SharePoint *", because I didn't encounter this issue during testing this functionality.

I will update the log name to SPDsc and push out a new version, v4.1.1

**Comment by ykuijs** [comment]
CD/CI is working on the preview release. Once that is done, I will push the formal v4.1.1 release which contains this fix. Will be sometime tomorrow (June 13th).

**Comment by ChristophHannappel** [comment]
Thanks the new versions works great.
