### ISSUE TITLE
SPManagedMetadataServiceAppDefault: Documentation is not up to date

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/SharePointDsc#1218]
#### Details of the scenario you tried and the problem that is occurring

Trying to provision Metadata Service Application connection

#### Suggested solution to the issue

Documentation https://github.com/dsccommunity/SharePointDsc/wiki/SPManagedMetaDataServiceAppDefault should be updated with current parameter set:

```
        [Parameter(Mandatory = $true)]
        [String]
        $ServiceAppProxyGroup,

        [Parameter(Mandatory = $true)]
        [System.String]
        $DefaultSiteCollectionProxyName,

        [Parameter(Mandatory = $true)]
        [System.String]
        $DefaultKeywordProxyName,

        [Parameter()]
        [System.Management.Automation.PSCredential]
        $InstallAccount
```
https://github.com/dsccommunity/SharePointDsc/blob/master/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.psm1

`IsSingleInstance` should be removed from documentation
`ServiceAppProxyGroup` should be added to documentation

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
            SPManagedMetaDataServiceAppDefault ManagedMetadataServiceAppDefault
            {
                IsSingleInstance                = "Yes"
                DefaultSiteCollectionProxyName  = "Managed Metadata Service Application"
                DefaultKeywordProxyName         = "Managed Metadata Service Application"
                PsDscRunAsCredential            = $SPInstallAccountCredential
                DependsOn                       = "[SPManagedMetaDataServiceApp]ManagedMetadataServiceApp"
            }
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2013

#### Version of the DSC module that was used

4.2.0

**Comment by ykuijs** [comment]
Ah yes, my apologies. Totally forgot to update the Wiki, thanks for letting me know!

FYI: We are working on an automated process to release documentation to the wiki, so this won't happen again ;-)
