### ISSUE TITLE
Invoke-SPDscCommand cannot be used in a Script resource since v3.8

### ISSUE THREAD

**Issue by Yvand** [dsccommunity/SharePointDsc#1222]
#### Details of the scenario you tried and the problem that is occurring

Since SharePointDsc 3.8, I can no longer use Invoke-SPDscCommand in a Script resource.

#### Verbose logs showing the problem

It fails with this error:
`PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The 
term 'Invoke-SPDscCommand' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.`

#### Suggested solution to the issue

I see in the [change log of 3.8](https://github.com/dsccommunity/SharePointDsc/releases/tag/v3.8.0) the following comment:
"Updated all resources and Invoke-SPDscCommand function to automatically
load Utils module, which broke with the new CI"
So I'm pretty sure it's related, although I didn't find the commit of this change so I don't know exactly what changed

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
Script ConfigureAppDomains
{
	SetScript = {
		$argumentList = @(@{ "webAppUrl"             = "http://$using:SPTrustedSitesName";
							 "AppDomainFQDN"         = "$using:AppDomainFQDN";
							 "AppDomainIntranetFQDN" = "$using:AppDomainIntranetFQDN" })
		Invoke-SPDscCommand -Arguments @argumentList -ScriptBlock {
			# CODE OMITTED
		}
	}
	GetScript            = { return @{ "Result" = "false" } }
	TestScript           = { return $false }
	PsDscRunAsCredential = $DomainAdminCredsQualified
}
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2019

#### Version and build of PowerShell the target node is running
                                                                           
PSVersion                      5.1.17763.1007                                                                           
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.17763.1007                                                                          
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1  

#### Version of the DSC module that was used

Repro with SharePointDsc 3.8+

**Comment by ykuijs** [comment]
Hi @Yvand This is correct. With the conversion to the new CD/CI pipeline using the internal SPDsc cmdlets no longer worked. Initially I had no clue why this happened, but recently someone pointed me to the right direction. I will add this cmdlets in a next version of SPDsc.
