### ISSUE TITLE
SPUserProfileServiceApp throws error interactive mode

### ISSUE THREAD

**Issue by mschaaks** [dsccommunity/SharePointDsc#1230]
This occurs using version 3.7.0.0 of SharePoint DS when deploying a SharePoint 2016 farm on Windows Server 2019 standard:

VERBOSE: [NLRTBSRV6SPWBD1]: [[SPUserProfileServiceApp]UserProfileServiceApplication] Executing using a provided credential and local PSSession as user **[user name]** PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt etc.

I did enable credssp on the machine, but did not check the presence of the mentioned SPN nor the group policy in this requirement, could that be related to my problem ?: 

The WinRM client cannot process the request.

CredSSP authentication is currently disabled in the client configuration. Change the client configuration and try the request again.

CredSSP authentication must also be enabled in the server configuration. Also, Group Policy must be edited to allow credential

delegation to the target computer. Use gpedit.msc and look at the following policy: Computer Configuration -> Administrative

Templates -> System -> Credentials Delegation -> Allow Delegating Fresh Credentials.  Verify that it is enabled and configured with

an SPN appropriate for the target computer. For example, for a target computer name "myserver.domain.com", the SPN can be one of the

following: WSMAN/myserver.domain.com or WSMAN/*.domain.com For more information, see the about_Remote_Troubleshooting Help topic

**Comment by ykuijs** [comment]
Hi @mschaaks How did you config CredSSP? Are you using the [xCredSSP resource](https://github.com/dsccommunity/SharePointDsc/wiki/Remote-sessions-and-the-InstallAccount-variable#option-2-configure-credssp-through-a-dsc-resource)? Can you share the commands used or the used config? And did you configure the client and server side of CredSSP?

**Comment by ykuijs** [comment]
@mschaaks Any update?

**Comment by ykuijs** [comment]
And can you share the output of Get-WSManCredSSP?

**Comment by ykuijs** [comment]
Unfortunately no response, which makes troubleshooting this issue impossible. Closing this issue.
