### ISSUE TITLE
Broken Example on SPServiceAppSecurity Wiki Page

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/SharePointDsc#1234]
On the https://github.com/dsccommunity/SharePointDsc/wiki/SPServiceAppSecurity page in Example 1, `@("Manage Profiles", "Manage Social Data")` does not go well together with `SecurityType         = "SharingPermissions"`. One of them should be changed.

**Comment by ykuijs** [comment]
Good spot. Will be corrected in my next bugfix PR.
