### ISSUE TITLE
[New Resource] SPService

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/SharePointDsc#1235]
### Description

In SharePoint 2016/2019 there is a new feature, service auto provisioning. A few corresponding PowerShell commands also were introduced:

- Get-SPService
- Start-SPService
- Stop-SPService

It would be nice to be able to use DSC to control auto provisioning of one or another service on the farm.

### Proposed properties

Pretty much the same as for
https://github.com/dsccommunity/SharePointDsc/wiki/SPServiceInstance

### Special considerations or limitations

**Comment by ykuijs** [comment]
We have the SPMinRole resource that checks if all servers are compliant with the MinRole configuration. Isn't this new resource overlapping (partly) with that resource?

Can you give an example in which scenario you would use this new resource?

**Comment by shurick81** [comment]
Hi, SPService should work together with SPMinRole, but not replacing one another.
The scenario is, for example, running "Microsoft SharePoint Foundation Sandboxed Code Service" service in the farm.

Here's how Microsoft offers to achieve that:
`Start-SPService -Identity "Microsoft SharePoint Foundation Sandboxed Code Service"`
https://docs.microsoft.com/th-th/powershell/module/sharepoint-server/start-spservice?view=sharepoint-ps

**Comment by ykuijs** [comment]
Properties:
```PowerShell
SPService 'SandboxCode'
{
    Name = 'Microsoft SharePoint Foundation Sandboxed Code Service'
    Ensure = 'Present' # Present=Running
    IncludeCustomServerRole = $false
}
```
