### ISSUE TITLE
[SharePointDsc HQRM] Update Pester tests to support Pester v5

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/SharePointDsc#1237]
Right now most Pester tests are using the v3 syntax, which is no longer working in Pester v5. The release process hasn't switched over to Pester v5 yet, but will in the future. This means we need to update the Pester tests to the most recent syntax.

**Comment by gaelcolas** [comment]
Bear in mind that PS5 does not yet support code coverage, so it's relatively low in the priority list (for Johan/Daniel and I at least).
That said, it's God to be prepared.

**Comment by ykuijs** [comment]
Fair point! My goal was to prepare SPDsc for PSv5 but not yet move over ;-)
