### ISSUE TITLE
[SPFarm] Resource cannot handle precreated databases

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/SharePointDsc#1241]
### Details of the scenario you tried and the problem that is occurring
If you precreate the Config and AdminContent databases in SharePoint, the logic in this resource does not detect that this is an empty database but assumes it is a fully provisioned database and tries to join the farm. This fails with the error message that is shown below.

#### Verbose logs showing the problem
```
Connect-SPConfigurationDatabase : There is a compatibility range mismatch between the Web server and database "", and connections to the data have been blocked to due to this incompatibility. This can happen when a content database has not been upgraded to be within the compatibility range of the Web server, or if the database has been upgraded to a higher level than the web server. The Web server and the database must be upgraded to the same version and build level to return to compatibility range.
At line:1 char:1
+ Connect-SPConfigurationDatabase -DatabaseName "SP_Config" -DatabaseSe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...urationDatabase:SPCmdletConnectSPConfigurationDatabase) [Connect-SPConfigurationDatabase], SPUpgradeCompatibilityExce 
   ption
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletConnectSPConfigurationDatabase

```

#### Suggested solution to the issue
Update the logic not only to check if the database exists, but also if any tables exist in the database. If there are not tables, it should still create the farm instead of trying to join.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of SharePoint that is used (e.g. SharePoint 2016)
Any

#### Version and build of PowerShell the target node is running
v5.1

#### Version of the DSC module that was used
dev

**Comment by ykuijs** [comment]
Am working on the fix, and will submit a PR soon

**Comment by Fiander** [comment]
Hi kyuijs,
If people are precreating databases, wouldn't that be because they don't want to give DBCreator rights?
If so, than the *_Lock database is a big pain that would prevent this.

Could the *_Lock database be changed in a *_Lock table in the TempDB?
This would allow to work without DBCreator,
Automatic backup procedures won't make a backup of the lock database.
when a installation fails, the table can be removed just like a database can be removed now, but a restart of the SQL Instance would also clean the TempDB, whereas a Lock database would still exists, and must still be cleaned manually.

**Comment by ykuijs** [comment]
Hi @Fiander, this is a very good point! In the case where I encountered this issue, not having DBCreator permissions isn't the reason why they were using precreated databases. They wanted to create databases with a specific configuration (number of data files, data file locations, etc.).

I will discuss your idea with some colleagues to see if we might overlook some issues when we implement this idea.

**Comment by ykuijs** [comment]
First fix has been pushed to master. Still looking into changing the Lock database to a Lock table.
