### ISSUE TITLE
SPInstallPrereqs Fails with Exit Code 1620

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/SharePointDsc#1252]
#### Details of the scenario you tried and the problem that is occurring

Due to the file http://go.microsoft.com/fwlink/?LinkId=622997 (SQL 2012 native client) is no longer available, SharePoint 2016 prerequisite installer cannot properly run and returns error.

#### Verbose logs showing the problem

```
PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error message:
The prerequisite installer ran with the following unknown exit code 1620
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SWAZSERVER01.c0nt0s00.local
```

#### Suggested solution to the issue

For example, one can use SQL 2012 SP4 native client. I tested it in my sandbox but not sure if it is fully supported by Microsoft:

```
        File SPLocalMediaEnsure {
            SourcePath = $env:SP_MEDIA_UNC
            DestinationPath = "C:\Install\SP_MEDIA"
            Recurse = $true
            Type = "Directory"
            Credential = $MediaShareCredential
        }

        xRemoteFile SQLNCli
        {
            Uri             = "https://download.microsoft.com/download/F/3/C/F3C64941-22A0-47E9-BC9B-1A19B4CA3E88/ENU/x64/sqlncli.msi"
            DestinationPath = "C:\Install\SP_MEDIA\2016\SharePoint\prerequisiteinstallerfiles\sqlncli.msi"
            MatchSource     = $false
            DependsOn       = "[File]SPLocalMediaEnsure"
        }

        Package SQLNCli
        {
            Path        = "C:\Install\SP_MEDIA\2016\SharePoint\prerequisiteinstallerfiles\sqlncli.msi"
            Name        = "Microsoft SQL Server 2012 Native Client "
            ProductId   = "B9274744-8BAE-4874-8E59-2610919CD419"
            Arguments   = "/qn /norestart IACCEPTSQLNCLILICENSETERMS=YES"
            DependsOn   = "[xRemoteFile]SQLNCli"
        }

        SPInstallPrereqs SPPrereqsInstalled
        {
            IsSingleInstance    = "Yes"
            InstallerPath       = "C:\Install\SP_MEDIA\2016\SharePoint\Prerequisiteinstaller.exe"
            OnlineMode          = $true
            DependsOn           = "[File]SPLocalMediaEnsure", "[Package]SQLNCli"
        }
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
        SPInstallPrereqs SPPrereqsInstalled
        {
            IsSingleInstance    = "Yes"
            InstallerPath       = "C:\Install\SP_MEDIA\2016\SharePoint\Prerequisiteinstaller.exe"
            OnlineMode          = $true
            DependsOn           = "[File]SPLocalMediaEnsure", "[Package]SQLNCli"
        }
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2016

#### Version of the DSC module that was used

4.2.0

**Comment by shurick81** [comment]
This page also, [Microsoft® SQL Server® 2012 Native Client - QFE](https://www.microsoft.com/en-us/download/details.aspx?id=50402) directs to https://download.microsoft.com/download/B/E/D/BED73AAC-3C8A-43F5-AF4F-EB4FEA6C8F3A/ENU/x64/sqlncli.msi, which is the same SQL 2012 SP4 as I wrote in the former comment. So this code also works:

```
        File SPLocalMediaEnsure {
            SourcePath = $env:SP_MEDIA_UNC
            DestinationPath = "C:\Install\SP_MEDIA"
            Recurse = $true
            Type = "Directory"
            Credential = $MediaShareCredential
        }

        xRemoteFile SQLNCli
        {
            Uri             = "https://download.microsoft.com/download/B/E/D/BED73AAC-3C8A-43F5-AF4F-EB4FEA6C8F3A/ENU/x64/sqlncli.msi"
            DestinationPath = "C:\Install\SP_MEDIA\2016\SharePoint\prerequisiteinstallerfiles\sqlncli.msi"
            MatchSource     = $false
            DependsOn       = "[File]SPLocalMediaEnsure"
        }

        Package SQLNCli
        {
            Path        = "C:\Install\SP_MEDIA\2016\SharePoint\prerequisiteinstallerfiles\sqlncli.msi"
            Name        = "Microsoft SQL Server 2012 Native Client "
            ProductId   = "B9274744-8BAE-4874-8E59-2610919CD419"
            Arguments   = "/qn /norestart IACCEPTSQLNCLILICENSETERMS=YES"
            DependsOn   = "[xRemoteFile]SQLNCli"
        }

        SPInstallPrereqs SPPrereqsInstalled
        {
            IsSingleInstance    = "Yes"
            InstallerPath       = "C:\Install\SP_MEDIA\2016\SharePoint\Prerequisiteinstaller.exe"
            OnlineMode          = $true
            DependsOn           = "[File]SPLocalMediaEnsure", "[Package]SQLNCli"
        }
```

**Comment by shurick81** [comment]
Brian promised to ask around also: https://github.com/brianlala/AutoSPSourceBuilder/issues/76

**Comment by ykuijs** [comment]
Hi @shurick81, thanks for reporting this! You are absolutely right that the package no longer is available for download. You have to use the package supplied with the SQL Server 2016 Feature Pack. That one is fully supported:
https://www.microsoft.com/en-us/download/details.aspx?id=56833

I will make sure the resource is updated, both documentation and the code handling the error message.

**Comment by shurick81** [comment]
Yes, so the prerequisite installer (and corresponding DSC resource) fails unless this component is preinstalled somehow before, from SQL Server 2016 Feature Pack SP2 or later version. I'm not sure, but maybe worth mentioning this in the DSC resource documentation?

**Comment by centuryx476** [comment]
Hello,
Can I download manually the sqlncli.msi and drop it into the "PrerequisiteInstallerFiles" folder ?
This Link: https://www.microsoft.com/en-us/download/details.aspx?id=56833

**Comment by shurick81** [comment]
I can try out. Do I have to specify the path in the SPInstallPrereqs resource?

**Comment by ykuijs** [comment]
@shurick81 I am updating both the documentation and the resource to refer to the Wiki when exit code 1620 is thrown.

@centuryx476 The resource does not process any of the specified prereq component parameters if you set OnlineMode to True. It will then always try to download any missing prereqs from the Internet.

**Comment by shurick81** [comment]
Prerequisite installer was failing because the permalink http://go.microsoft.com/fwlink/?LinkId=622997 was pointing to https://download.microsoft.com/download/4/B/1/4B1E9B0E-A4F3-4715-B417-31C82302A70A/ENU/x64/sqlncli.msi, that is not available anymore. Now thanks to @brianlala, Microsoft has fixed the permalink and it points to SQL 2012 SP4 Native Client, https://download.microsoft.com/download/F/3/C/F3C64941-22A0-47E9-BC9B-1A19B4CA3E88/ENU/x64/sqlncli.msi. Everything should now work as before the incident (but installing a new version of the client).

**Comment by ykuijs** [comment]
Since this issue is resolved (thanks @brianlala) I am going to close this issue.
