### ISSUE TITLE
SPWebAppPolicy parameter type mismatch for Identity

### ISSUE THREAD

**Issue by jensotto** [dsccommunity/SharePointDsc#1262]
#### Details of the scenario you tried and the problem that is occurring

Any use of the SPWebAppPolicy resource.

#### Verbose logs showing the problem

PowerShell DSC resource MSFT_SPWebAppPolicy failed to execute Test-TargetResource functionality with error message:
Cannot convert 'System.Object[]' to the type 'Microsoft.SharePoint.PowerShell.SPWebApplicationPipeBind' required by
parameter 'Identity'. Specified method is not supported.
+ CategoryInfo : InvalidOperation: (:) [], CimException
+ FullyQualifiedErrorId : ProviderOperationExecutionFailure
+ PSComputerName : localhost

#### Suggested solution to the issue

Change parameter type for $InputParameters from array of Object to string in Get-SPDscCacheAccountConfiguration

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
            SPWebAppPolicy DefaultWebApplication
            {
                PsDscRunAsCredential = $SPSetupCredential;
                SetCacheAccountsPolicy = $true;
                WebAppUrl = $ConfigurationData.NonNodeData.WebAppUrl;
                Members = $defaultWebApplicationPolicyUserMembers;
            }
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2019

#### Version and build of PowerShell the target node is running

5.1.17763.1490

#### Version of the DSC module that was used

4.4.0

**Comment by ykuijs** [comment]
Thanks for creating this issue!

Fixed in PR #1261, merged into Dev
