### ISSUE TITLE
SPConfigWizard fails

### ISSUE THREAD

**Issue by ThomasLie** [dsccommunity/SharePointDsc#1277]
#### Details of the scenario you tried and the problem that is occurring
When installing a CU using SPProductUpdate and executing SPConfigWizard it fails on all SharePoint servers except those with MinRole Search.

When executing PSConfig manually on these servers, it completes successfully.

Any help is aprreciated....

#### Verbose logs showing the problem
12/17/2020 12:42:31.91 PSCONFIG (0x07A8)       0x0EF4  SharePoint Foundation Upgrade                SPIisWebSiteWssSequence       ajywk    ERROR  Action 16.0.13.0 of Microsoft.SharePoint.Upgrade.SPIisWebSiteWssSequence failed.        00000000-0000-0000-0000-000000000000
12/17/2020 12:42:31.91 PSCONFIG (0x07A8)       0x0EF4  SharePoint Foundation Upgrade                SPIisWebSiteWssSequence       ajywk    ERROR  Exception: Filename: \\?\C:\WINDOWS\system32\inetsrv\config\applicationHost.config  Error:               00000000-0000-0000-0000-000000000000
12/17/2020 12:42:31.91 PSCONFIG (0x07A8)       0x0EF4  SharePoint Foundation Upgrade                SPIisWebSiteWssSequence       ajywk    ERROR     at Microsoft.Web.Administration.Interop.IAppHostAdminManager.GetAdminSection(String bstrSectionName, String bstrPath)     at Microsoft.Web.Administration.Configuration.GetSectionInternal(ConfigurationSection section, String sectionPath, String locationPath)     at Microsoft.Web.Administration.ServerManager.SitesSectionCreator()     at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)     at Microsoft.Web.Administration.ServerManager.SitesCollectionCreator()     at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)     at Microsoft.SharePoint.Administration.SPIisVirtualDirectory..ctor(SPIisWebSite parent, String path)     at Microsoft.SharePoint.Upgrade.SPWebConfigIisSiteAction.get_AppWebConfigPath()     at Microsoft.SharePoint.Upgrade.RemoveJsonHandlerForVroom.Upgrade()     at Microsoft.SharePoint.Upgrade.SPActionSequence.Upgrade() 00000000-0000-0000-0000-000000000000

12/17/2020 12:42:32  15  ERR            An exception of type Microsoft.SharePoint.Upgrade.SPUpgradeException was thrown.  Additional exception information: Action 16.0.13.0 of Microsoft.SharePoint.Upgrade.SPIisWebSiteWssSequence failed.
Microsoft.SharePoint.Upgrade.SPUpgradeException: Action 16.0.13.0 of Microsoft.SharePoint.Upgrade.SPIisWebSiteWssSequence failed. ---> System.Runtime.InteropServices.COMException: Filename: \\?\C:\WINDOWS\system32\inetsrv\config\applicationHost.config
Error: 
   at Microsoft.Web.Administration.Interop.IAppHostAdminManager.GetAdminSection(String bstrSectionName, String bstrPath)
   at Microsoft.Web.Administration.Configuration.GetSectionInternal(ConfigurationSection section, String sectionPath, String locationPath)
   at Microsoft.Web.Administration.ServerManager.SitesSectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.Web.Administration.ServerManager.SitesCollectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.SharePoint.Administration.SPIisVirtualDirectory..ctor(SPIisWebSite parent, String path)
   at Microsoft.SharePoint.Upgrade.SPWebConfigIisSiteAction.get_AppWebConfigPath()
   at Microsoft.SharePoint.Upgrade.RemoveJsonHandlerForVroom.Upgrade()
   at Microsoft.SharePoint.Upgrade.SPActionSequence.Upgrade()
   --- End of inner exception stack trace ---
   at Microsoft.SharePoint.Upgrade.SPActionSequence.Upgrade()
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.RunUpgraders(Object o, List`1 lstClass)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.Upgrade(Object o, Boolean bRecurse)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.ReflexiveUpgrade(Object o, Boolean bRecurse)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.RunRecursiveUpgrade(Object o, Boolean bNeedsUpgrade, SPTree`1 root, Double rootRatioOrg, SPChronoMeter chronoMeter)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.Upgrade(Object o, Boolean bRecurse)
   at Microsoft.SharePoint.Administration.SPPersistedUpgradableObject.Upgrade(Boolean recursively)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.ReflexiveUpgrade(Object o, Boolean bRecurse)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.RunRecursiveUpgrade(Object o, Boolean bNeedsUpgrade, SPTree`1 root, Double rootRatioOrg, SPChronoMeter chronoMeter)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.Upgrade(Object o, Boolean bRecurse)
   at Microsoft.SharePoint.Administration.SPPersistedUpgradableObject.Upgrade(Boolean recursively)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.ReflexiveUpgrade(Object o, Boolean bRecurse)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.RunRecursiveUpgrade(Object o, Boolean bNeedsUpgrade, SPTree`1 root, Double rootRatioOrg, SPChronoMeter chronoMeter)
   at Microsoft.SharePoint.Upgrade.SPUpgradeSession.Upgrade(Object o, Boolean bRecurse)
   at Microsoft.SharePoint.Upgrade.SPManager.InplaceUpgradeAdministrationWebApplication()
   at Microsoft.SharePoint.PostSetupConfiguration.UpgradeTask.Run()
   at Microsoft.SharePoint.PostSetupConfiguration.TaskThread.ExecuteTask()

#### The operating system the target node is running
Windows Server 2016

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used
4.4.0

**Comment by ThomasLie** [comment]
Hey guys,

as it is quite urgent...does anyone have a clue?

Regards
Thomas

**Comment by ykuijs** [comment]
Hi @ThomasLie Can you share your DSC config? Did you specify the PSDscRunAsCredential parameter for SPConfigWizard?

**Comment by ThomasLie** [comment]
Hi Yorick,

I specified the PSDscRunAsCredential parameter.

Btw, when executing PSConfig locally on a SharePoint server it completes successfully. Then running PSConfig with DSC again it will complete successfully until I install another CU.

I can reproduce this behaviour on each CU installation at different customer environments.

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT Consulting & Hausverwaltung GbR
Römerweg 10a
63303 Dreieich - Germany

Fon: +49 171.2625166
Email: thomas@lieftuechter.de<mailto:thomas@lieftuechter.de>
Web:  https://www.lieftuechter.com/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Yorick Kuijs <notifications@github.com>
Gesendet: Donnerstag, 14. Januar 2021 14:57
An: dsccommunity/SharePointDsc <SharePointDsc@noreply.github.com>
Cc: Thomas Lieftüchter <thomas@lieftuechter.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dsccommunity/SharePointDsc] SPConfigWizard fails (#1277)


Hi @ThomasLie<https://github.com/ThomasLie> Can you share your DSC config? Did you specify the PSDscRunAsCredential parameter for SPConfigWizard?

**Comment by ThomasLie** [comment]
Hi Yorick,

hre ist he current configuration…

@{
    AllNodes = @(
        @{
            ### Einstellungen für alle Server ###
                                               NodeName                                                                       = "*"
            AzureDeployment                                            = $true
                                               PSDscAllowPlainTextPassword = $true
            PSDscAllowDomainUser                 = $true
            InstallProductUpdate                      = $true
        },
                               @{
                                               NodeName                        = "AppServer1"
                                               IsMasterNode = $true
                                               ServerRole      = "Application"
                                               ServiceRoles      = @{
                                                               WebFrontEnd                   = $false
                                                               DistributedCache            = $false
                                                               Application                        = $true
                                                               Search                                                  = $false
                                               }
        },
                               @{
                                               NodeName                        = "AppServer2"
                                               IsMasterNode = $false
                                               ServerRole      = "Application"
                                               ServiceRoles      = @{
                                                               WebFrontEnd                   = $false
                                                               DistributedCache            = $false
                                                               Application                        = $true
                                                               Search                                                  = $false
                                               }
        },
        @{
                                               NodeName                        = "WFEServer1"
                                               IsMasterNode = $false
                                               ServerRole      = "WebFrontEndWithDistributedCache"
                                               ServiceRoles      = @{
                WebFrontEnd                 = $true
                DistributedCache           = $true
                Application                       = $false
                Search                                                               = $false
            }
                               },
                               @{
                                               NodeName                        = "WFEServer2"
                                               IsMasterNode = $false
                                               ServerRole      = "WebFrontEndWithDistributedCache"
                                               ServiceRoles      = @{
                WebFrontEnd                 = $true
                DistributedCache           = $true
                Application                       = $false
                Search                                                               = $false
            }
        },
                               @{
                                               NodeName                        = "SearchServer1"
                                               IsMasterNode = $false
                                               ServerRole      = "Search"
                                               ServiceRoles      = @{
                WebFrontEnd                 = $false
                DistributedCache           = $false
                Application                       = $false
                Search                                                               = $true
                                               }
        },
                               @{
                                               NodeName                        = "SearchServer2"
                                               IsMasterNode = $false
                                               ServerRole      = "Search"
                                               ServiceRoles      = @{
                WebFrontEnd                 = $false
                DistributedCache           = $false
                Application                       = $false
                Search                                                               = $true
                                               }
                               }
    )

                NonNodeData = @{

                               SharePoint = @{
            ProductUpdate = @{
               STSFile = "sts2019-kb4464518-fullfile-x64-glb.exe"
                                                  WSSFile = "wssloc2019-kb4462221-fullfile-x64-glb.exe"
            }

                                               ServiceAccounts = @(
                                                               @{
                                                                               Name     = "SetupAccount"
                                                                               Username = "contoso\SP19-00-SETUP"
                                                               }
                                               )
        }
    }
}

Configuration SharePointConfigureUpdates
{
    param (
        [Parameter(Mandatory=$true)] $SPSetupAccount
    )

    Import-DscResource -ModuleName PSDesiredStateConfiguration
                Import-DscResource -ModuleName SharePointDSC -ModuleVersion '4.4.0'

                node $AllNodes.NodeName
    {
        #**********************************************************
        # Server configuration
        #**********************************************************

                               # Section UAC settings
        Registry DisableLUA {
                Key       = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
                ValueName = 'EnableLUA'
                ValueData = '0'
                ValueType = 'DWORD'
                Force     = $true
        }
        Registry DisableUAC1 {
                Key       = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
                ValueName = 'ConsentPromptBehaviorAdmin'
                ValueData = '0'
                ValueType = 'DWORD'
                Force     = $true
        }
        Registry DisableUAC2 {
                Key       = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
                ValueName = 'PromptOnSecureDesktop'
                ValueData = '0'
                ValueType = 'DWORD'
                Force     = $true
        }

        if ($Node.InstallProductUpdate -eq $true)
        {
            SPConfigWizard RunConfigWizard
                                               {
                                                               IsSingleInstance     = "Yes"
                                                               PsDscRunAsCredential = $SPSetupAccount
                                               }
                                               $FarmWaitTask = "[SPConfigWizard]RunConfigWizard"

            Service SPTimerV4
                                               {
                                                               Name                 = "SPTimerV4"
                StartupType          = "Automatic"
                State                = "Running"
                                                               PsDscRunAsCredential = $SPSetupAccount
                Dependson            = $FarmWaitTask
                                               }

            Service SPAdminV4
                                               {
                                                               Name                 = "SPAdminV4"
                StartupType          = "Automatic"
                State                = "Running"
                                                               PsDscRunAsCredential = $SPSetupAccount
                Dependson            = $FarmWaitTask
                                               }

            Service W3SVC
                                               {
                                                               Name                 = "W3SVC"
                StartupType          = "Automatic"
                State                = "Running"
                                                               PsDscRunAsCredential = $SPSetupAccount
                Dependson            = $FarmWaitTask
                                               }

            if ($Node.ServerRole -like "*Distributed*")
            {
                Service AppFabricCachingService
                                                   {
                                                                   Name                 = "AppFabricCachingService"
                    StartupType          = "Automatic"
                    State                = "Running"
                                                                   PsDscRunAsCredential = $SPSetupAccount
                    Dependson            = $FarmWaitTask
                                                   }
            }

            if ($Node.ServerRole -like "*Search*")
            {
                Service OSearch16
                                                   {
                                                                   Name                 = "OSearch16"
                    StartupType          = "Manual"
                    State                = "Running"
                                                                   PsDscRunAsCredential = $SPSetupAccount
                    Dependson            = $FarmWaitTask
                                                   }

                Service SPSearchHostController
                                                   {
                                                                   Name                 = "SPSearchHostController"
                    StartupType          = "Automatic"
                    State                = "Running"
                                                                   PsDscRunAsCredential = $SPSetupAccount
                    Dependson            = $FarmWaitTask
                                                   }
            }

            if ($Node.ServerRole -eq "Custom")
            {
                if ($Node.ServerRoles.DistributedCache -eq $true)
                {
                    Service AppFabricCachingService
                                                       {
                                                                       Name                 = "AppFabricCachingService"
                        StartupType          = "Automatic"
                        State                = "Running"
                                                                       PsDscRunAsCredential = $SPSetupAccount
                        Dependson            = $FarmWaitTask
                                                       }
                }

                if ($Node.ServerRoles.Search -eq $true)
                {
                    Service OSearch16
                                                       {
                                                                       Name                 = "OSearch16"
                        StartupType          = "Manual"
                        State                = "Running"
                                                                       PsDscRunAsCredential = $SPSetupAccount
                        Dependson            = $FarmWaitTask
                                                       }

                    Service SPSearchHostController
                                                       {
                                                                       Name                 = "SPSearchHostController"
                        StartupType          = "Automatic"
                        State                = "Running"
                                                                       PsDscRunAsCredential = $SPSetupAccount
                        Dependson            = $FarmWaitTask
                                                       }
                }

                if ($Node.ServerRoles.Application -eq $true -or $Node.ServerRoles.WebFrontEnd -eq $true)
                {
                    Service C2WTS
                                                       {
                                                                       Name                 = "c2wts"
                        StartupType          = "Automatic"
                        State                = "Running"
                                                                       PsDscRunAsCredential = $SPSetupAccount
                        Dependson            = $FarmWaitTask
                                                       }
                }
            }
        }
                }
}

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT Consulting & Hausverwaltung GbR
Römerweg 10a
63303 Dreieich - Germany

Fon: +49 171.2625166
Email: thomas@lieftuechter.de<mailto:thomas@lieftuechter.de>
Web:  https://www.lieftuechter.com/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Yorick Kuijs <notifications@github.com>
Gesendet: Donnerstag, 14. Januar 2021 14:57
An: dsccommunity/SharePointDsc <SharePointDsc@noreply.github.com>
Cc: Thomas Lieftüchter <thomas@lieftuechter.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dsccommunity/SharePointDsc] SPConfigWizard fails (#1277)


Hi @ThomasLie<https://github.com/ThomasLie> Can you share your DSC config? Did you specify the PSDscRunAsCredential parameter for SPConfigWizard?

**Comment by ykuijs** [comment]
Thanks for this information @ThomasLie. So far I haven't any clue what might be causing this. It is the first time I see this error and I have recently deployed several environments with the same versions of Windows and SharePoint.

Can you share the verbose output of the deployment as well?

**Comment by ykuijs** [comment]
Please share as much as possible, not just the lines with the errors. I am trying to track down where this goes wrong.

**Comment by ThomasLie** [comment]
Hi Yorick,

please find attached a part of the Upgrade log…

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT Consulting & Hausverwaltung GbR
Römerweg 10a
63303 Dreieich - Germany

Fon: +49 171.2625166
Email: thomas@lieftuechter.de<mailto:thomas@lieftuechter.de>
Web:  https://www.lieftuechter.com/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Yorick Kuijs <notifications@github.com>
Gesendet: Mittwoch, 20. Januar 2021 13:48
An: dsccommunity/SharePointDsc <SharePointDsc@noreply.github.com>
Cc: Thomas Lieftüchter <thomas@lieftuechter.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dsccommunity/SharePointDsc] SPConfigWizard fails (#1277)


Please share as much as possible, not just the lines with the errors. I am trying to track down where this goes wrong.

**Comment by ykuijs** [comment]
Hi @ThomasLie there is no log attached. And do you also have the verbose logging output?

**Comment by ykuijs** [comment]
Discussed offline with Thomas. Looks like an issue with SharePoint itself, issue also occurs with PowerShell Remoting only (no DSC). They have raised a support case for this issue. Waiting for the results of that.

**Comment by ThomasLie** [comment]
Hi Yorick,

short update on this:

Currently working with Vlad on this issue, it seems the changes in applicationHost.config (implemented with March 2020 CU) causes the issue. In Windows Eventlog 2 errors came up related to ntdll.dll and clr.dll.
Looks like a permission issue, however the account running psconfig remotely is local admin on each of the SharePoint servers....

We're still investigating, will keep you updated...

**Comment by ThomasLie** [comment]
HI Yorick,

working with Rainer A. on the isue and we're very close to a solution upgrading a farm remotly.

First we're upgrading the content databases, then running these CMDLets on each server:

`Install-SPHelpCollection -All
Initialize-SPResourceSecurity
Install-SPService
Install-SPFeature -AllExistingFeatures
Install-SPApplicationContent
Upgrade-SPFarm -ServerOnly -SkipDatabaseUpgrade -SkipSiteUpgrade`

Once this has finished we're upgrading the farm on the application server hosting Central Admin site:

`# Waiting for the 'HelpCollectionInstallerJob' job:
while (!(($waitcount -gt 60) -or ((Get-SPTimerJob | ? { $_.Typename -eq "Microsoft.SharePoint.Help.HelpCollectionInstallerJob" }) -eq $null)))
{
	$waitcount +=1
			
	Write-Verbose -Message  "[$($Env:COMPUTERNAME)] Help Collection Installer timer jobs are still running..." 
            
	Start-Sleep 10
}

# Upgrading the farm
Upgrade-SPFarm

# Wait for the Product Version Timer Job
Get-SPTimerJob -Identity "job-admin-product-version" | Start-SPTimerJob
Start-Sleep 480`

Once this has finished, we have a fully upgraded farm, but....

The above code only works if we do not have a search application. 

Havin a search application in place the upgrade fails with this error:

03/16/2021 16:57:22.34	wsmprovhost (0x0C0C)	0x1950	SharePoint Foundation Upgrade	SPUpgradeSession	an59t	ERROR	Upgrade [SearchAdminDatabase Name=SP19_01_S_SEARCH_DB_001] failed.	e3deb49f-02f1-1029-ffc2-b85919818a02
03/16/2021 16:57:22.34	wsmprovhost (0x0C0C)	0x1950	SharePoint Foundation Upgrade	SPUpgradeSession	an59t	ERROR	Exception: **No mapping between account names and security IDs was done**	e3deb49f-02f1-1029-ffc2-b85919818a02
03/16/2021 16:57:22.34	wsmprovhost (0x0C0C)	0x1950	SharePoint Foundation Upgrade	SPUpgradeSession	an59t	ERROR	   at Microsoft.Office.Server.Utilities.WindowsSecurity.LookupAccountName(String accountName, String& domainName, SID_NAME_USE& use)     at Microsoft.Office.Server.Utilities.WindowsSecurity.GetNT4AccountName(String name)     at Microsoft.Office.Server.Data.SqlServerManager.GrantLogin(String user)     at Microsoft.Office.Server.Search.Administration.SearchDatabase.GrantDatabaseRole(String username, String role)     at Microsoft.Office.Server.Search.Administration.SearchDatabase.AddUsersToSearchAdminRole(SearchServiceApplication searchApp)     at Microsoft.Office.Server.Search.Administration.SearchServiceApplication.UpdateAccessRulesForDatabases()     at Microsoft.Office.Server.Search.Upgrade.SearchAdminDatabaseSequence.PostUpgrade()     at Microsoft.SharePoint.Upgrade.SPUpgradeSession.RunPostUpgraders(Object o, List`1 lstClass)     at Microsoft.SharePoint.Upgrade.SPUpgradeSession.Upgrade(Object o, Boolean bRecurse)	e3deb49f-02f1-1029-ffc2-b85919818a02

We're currently investigating....any input on this is appreciated ;-)

Regards
Thomas

**Comment by ThomasLie** [comment]
Hi there,

we resolved the issue with upgrading search. Root cause was an AD group with specific permissions on the database.

Furthermore we do hab a workaround for the PSConfig issue:

We're able to ugrade the complete farm by running `Upgade-SPFarm -ServerOnly` on each server before executing psconfig.

We've tested this several times on different farms and it works like a charm...

I suggest to update the resource MSFT_SPConfigWizard with this.

Regards,
Thomas

**Comment by ykuijs** [comment]
This is great news. Just one question so understand the procedure correctly. Do we

1. Have to run this command on all servers in the farm before we can run the psconfig command on the first server in the farm. So Upgrade-SPFarm on server1 and server2 and then psconfig on server1 and server 2

or

2. Run this command on each server before we run the psconfig command on that same server. So Upgrade-SPFarm on server1 followed by psconfig on server1 and then Upgrade-SPFarm on server2 followed by psconfig on server2, etc?

I seriously hope it is option 2, since that is way easier to implement 😜

**Comment by ThomasLie** [comment]
Hi Yorick,

it is option 2, we have have to run it just before Psconfig on each server...

So it is just one line of code to add...

Btw, what do you think about a resource for upgrading content databases?

Mit freundlichen Grüßen

Thomas Lieftüchter

Lieftüchter IT-Consulting & Hausverwaltung GbR
Römerweg 10a
63303 Dreieich - Germany
Fon: +49 171.2625166
Email: ***@***.***
Web: http://www.lieftuechter.com/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
________________________________
Von: Yorick Kuijs ***@***.***>
Gesendet: Thursday, April 29, 2021 9:43:46 PM
An: dsccommunity/SharePointDsc ***@***.***>
Cc: Thomas Lieftüchter ***@***.***>; Mention ***@***.***>
Betreff: Re: [dsccommunity/SharePointDsc] SPConfigWizard fails (#1277)


This is great news. Just one question so understand the procedure correctly. Do we

  1.  Have to run this command on all servers in the farm before we can run the psconfig command on the first server in the farm. So Upgrade-SPFarm on server1 and server2 and then psconfig on server1 and server 2

or

  1.  Run this command on each server before we run the psconfig command on that same server. So Upgrade-SPFarm on server1 followed by psconfig on server1 and then Upgrade-SPFarm on server2 followed by psconfig on server2, etc?

I seriously hope it is option 2, since that is way easier to implement 😜

**Comment by ykuijs** [comment]
That is great, then it indeed would be simply adding one line 😄

What exactly is your idea behind upgrading a content database? Attaching a database from a previous SharePoint version (migration)? Or upgrading a database that is running in backwards compatibility mode?

In either case, it would make sense to extend the SPContentDatabase to allow this. Haven't tested this yet, but I think the resource already upgrades a database from a previous SP version (it uses Mount-SPContentDatabase, which upgrades the DB when needed). For databases in backwards compatibility mode we could add a parameter like PerformUpgrade, which is false by default. If you specify that parameter as true, the resource upgrades the databases when needed.

**Comment by ThomasLie** [comment]
I like the idea to add a new parameter...
However, this should run before psconfig and should allow to perform a parallel upgrade...
Actually, I do have some code for this 😉

Mit freundlichen Grüßen

Thomas Lieftüchter

Lieftüchter IT-Consulting & Hausverwaltung GbR
Römerweg 10a
63303 Dreieich - Germany
Fon: +49 171.2625166
Email: ***@***.***
Web: http://www.lieftuechter.com/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
________________________________
Von: Yorick Kuijs ***@***.***>
Gesendet: Thursday, April 29, 2021 10:14:18 PM
An: dsccommunity/SharePointDsc ***@***.***>
Cc: Thomas Lieftüchter ***@***.***>; Mention ***@***.***>
Betreff: Re: [dsccommunity/SharePointDsc] SPConfigWizard fails (#1277)


That is great, then it indeed would be simply adding one line 😄

What exactly is your idea behind upgrading a content database? Attaching a database from a previous SharePoint version (migration)? Or upgrading a database that is running in backwards compatibility mode?

In either case, it would make sense to extend the SPContentDatabase to allow this. Haven't tested this yet, but I think the resource already upgrades a database from a previous SP version (it uses Mount-SPContentDatabase, which upgrades the DB when needed). For databases in backwards compatibility mode we could add a parameter like PerformUpgrade, which is false by default. If you specify that parameter as true, the resource upgrades the databases when needed.
