### ISSUE TITLE
New resource 'SPFixRoleCompliance' for fixing MinRole compliance

### ISSUE THREAD

**Issue by ThomasLie** [dsccommunity/SharePointDsc#1280]
### Description
Sometimes when joining servers with MinRole 'DistributedCache' or 'WebFrontEndWith DistributedCache' the servers are not compliant with configured MinRole.
The new resource 'SPFixRoleCompliance' will fix this.

[MSFT_SPFixRoleCompliance.zip](https://github.com/dsccommunity/SharePointDsc/files/5856243/MSFT_SPFixRoleCompliance.zip)

It's already been tested in a couple of environments.

### Proposed properties
IsSingleInstance     = 'Yes'
PsDscRunAsCredential = $SPSetupAccount
Ensure               = 'Present'

### Special considerations or limitations
None

**Comment by ThomasLie** [comment]
Hi guys,

attached is a little fix in the resource...

[MSFT_SPFixRoleCompliance.zip](https://github.com/dsccommunity/SharePointDsc/files/5865635/MSFT_SPFixRoleCompliance.zip)

**Comment by ykuijs** [comment]
Hi @ThomasLie, I haven't looked at the code yet, but have you checked/tested the SPMinRole resource? Sounds like this resource is very similar.

**Comment by ThomasLie** [comment]
Hi Yorick,

I had a look at the code of the SPMinRole resource. Mine has a different approach, maybe it makes sense to merge the two resources?

Mit freundlichen Grüßen / Kind regards

Thomas Lieftüchter

Lieftüchter IT Consulting & Hausverwaltung GbR
Römerweg 10a
63303 Dreieich - Germany

Fon: +49 171.2625166
Email: thomas@lieftuechter.de<mailto:thomas@lieftuechter.de>
Web:  https://www.lieftuechter.com/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Yorick Kuijs <notifications@github.com>
Gesendet: Dienstag, 26. Januar 2021 20:29
An: dsccommunity/SharePointDsc <SharePointDsc@noreply.github.com>
Cc: Thomas Lieftüchter <thomas@lieftuechter.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dsccommunity/SharePointDsc] New resource 'SPFixRoleCompliance' for fixing MinRole compliance (#1280)


Hi @ThomasLie<https://github.com/ThomasLie>, I haven't looked at the code yet, but have you checked/tested the SPMinRole resource? Sounds like this resource is very similar.

**Comment by ykuijs** [comment]
@ThomasLie Have been reviewing your code and comparing it against the MinRoleCompliance resource.

The MinRoleCompliance checks if all services in the farm are compliant with the MinRole definition and performs corrective actions if required. It does this for all servers in the farm.

You code checks if a specific server is compliant and if it is not, runs the following cmdlets:
```PowerShell
Write-Verbose -Message "Starting Initialize-SPResourceSecurity"
Initialize-SPResourceSecurity | Out-Null
				
Write-Verbose -Message "Starting Install-SPService"
Install-SPService | Out-Null
				
Write-Verbose -Message "Starting Install-SPFeature"
Install-SPFeature -AllExistingFeatures -Force | Out-Null
				
Write-Verbose -Message "Installing application content files"
Install-SPApplicationcontent | Out-Null
```

It is a bit unclear why you run these cmdlets if a server is not compliant with the MinRole. Can you explain a little more?

Also:
These cmdlets are ran during the creation of the farm in SPFarm resource. That resource sound like a better place for this logic, but before that we need specific logic to check if the cmdlets need to get run or not (and specify if the resource is in the Desired State or not).

**Comment by ThomasLie** [comment]
Isuue can be closed.
