### ISSUE TITLE
Test-TargetResource: All resources fails

### ISSUE THREAD

**Issue by jensotto** [dsccommunity/SharePointDsc#1284]
#### Details of the scenario you tried and the problem that is occurring

After upgrading from 4.4.0 to 4.5.0 and installing ReverseDSC **all** SharePointDSC resources fails on the Test-TargetResource with the following error:

**An item with the same key has already been added.**

#### Verbose logs showing the problem

VERBOSE: [--server--]: LCM:  [ Start  Resource ]  [[SPFarm]SharePointFarm]
VERBOSE: [--server--]: LCM:  [ Start  Test     ]  [[SPFarm]SharePointFarm]
PowerShell DSC resource MSFT_SPFarm  failed to execute Test-TargetResource functionality with error
message: An item with the same key has already been added.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : --server--

VERBOSE: [--server--]:                            [] Consistency check completed.
VERBOSE: [--server--]:                            [[SPFarm]SharePointFarm] Testing local SP Farm
settings
VERBOSE: [--server--]:                            [[SPFarm]SharePointFarm] Getting the settings of the
 current local SharePoint Farm (if any)
VERBOSE: [--server--]:                            [[SPFarm]SharePointFarm] Detected installation of
SharePoint 2019
VERBOSE: [--server--]:                            [[SPFarm]SharePointFarm] This node has already been
connected to a farm
VERBOSE: [--server--]:                            [[SPFarm]SharePointFarm] Executing as the local run
as user AD\SetupAccount
VERBOSE: [--server--]: LCM:  [ End    Test     ]  [[SPFarm]SharePointFarm]  in 0.5780 seconds.
The SendConfigurationApply function did not succeed. LCM failed to start desired state configuration
manually.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimExceptio
   n
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : --server--

VERBOSE: Operation 'Invoke CimMethod' complete.
PowerShell DSC resource MSFT_SPFarm  failed to execute Test-TargetResource functionality with error
message: An item with the same key has already been added.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : --server--

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used

Name          Version Path
----          ------- ----
SharePointDSC 4.5.0   C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\4.5.0\SharePointDSC.psd1

**Comment by jensotto** [comment]
Commenting out the following line seems to remove the error message (but of course is not a viable option). I don't understand why that line is problematic, and there has been no changes to that in ages. It runs just fine if executed directly in a PowerShell session on the same server. I've tried to restart the server too. https://github.com/dsccommunity/SharePointDsc/blob/68297c97fc2ea10e12a5536c390ebcb2a0be2d20/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L621 removes the error,

**Comment by jensotto** [comment]
Just to be clear, I also tried to remove $ScriptBlock.ToString() so that there are no side effects of removing line 621
https://github.com/dsccommunity/SharePointDsc/blob/68297c97fc2ea10e12a5536c390ebcb2a0be2d20/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L627

**Comment by jensotto** [comment]
Also, it's this line that generates the exception: https://github.com/dsccommunity/SharePointDsc/blob/68297c97fc2ea10e12a5536c390ebcb2a0be2d20/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L650

**Comment by jensotto** [comment]
I managed to get this stack trace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.PowerShell.Commands.AddPSSnapinCommand.AddPSSnapIns(Collection`1 snapInList)
   at Microsoft.PowerShell.Commands.AddPSSnapinCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-SPDscCommand
    + PSComputerName        : localhost

It doens't look like it's related to SharePointDSC, but if I revert to v 4.4.0 everything works just fine.

**Comment by jensotto** [comment]
I have tried to use both sharepointdsc.4.5.0-preview0001 and sharepointdsc.4.5.0-preview0002. Both works just fine. There must have been something introduced after sharepointdsc.4.5.0-preview0002.

**Comment by jensotto** [comment]
I've found that removing this fixes the issue
https://github.com/dsccommunity/SharePointDsc/blob/68297c97fc2ea10e12a5536c390ebcb2a0be2d20/SharePointDsc/Modules/SharePointDsc.Reverse/Import-SPPowerShellSnapIn.ps1#L3

It will probably break some functionality of SharePointDSC. Do you have any solution @ykuijs ?

**Comment by ykuijs** [comment]
Hi @jensotto,

Hmm, I did several tests before releasing v4.5, but didn't run into this issue 😢 Thanks for reporting it!

This issue is caused by the fact that SharePoint is still using snap-ins instead of modules. Snapins can only be loaded once, but can't be dectected properly across scopes. If you try to load the snapin twice you get the error you encountered here: "An item with the same key has already been added" But if you do a Get-PSSnapin at the same location, the SharePoint snapin would be returned 😠

This is the exact issue that prevented us from integrating ReverseDsc into SharePointDsc earlier. The ScriptsToProcess parameter solved this issue for us, but as it appears not entirely. Let me troubleshoot/test this some more!

**Comment by ykuijs** [comment]
Just tested a resource and am able to reproduce the issue. Am 100% this worked during testing, so not sure what has happened here. Now checking where this is coming from and looking for a solution!

**Comment by ykuijs** [comment]
@jensotto Could you please test the following solution:

Add the following two lines to the SPFarm resource at the top of the file (just before the Get-TargetResource method) and let me know if this works or not?

```PowerShell
$script:SPDscUtilModulePath = Join-Path -Path $PSScriptRoot -ChildPath '..\..\Modules\SharePointDsc.Util\SharePointDsc.Util.psm1'
Import-Module -Name $script:SPDscUtilModulePath
```

**Comment by ykuijs** [comment]
If this works for the SPFarm resource, it should also work for other resources.

**Comment by jensotto** [comment]
No, sorry I still get the same error.

**Comment by ykuijs** [comment]
Did you by any chance run the test shortly after a regular run? The LCM caches the code files so changes are only picked up after a while. Either reboot the machine or change the ForceModuleImport parameter of the LCM.

**Comment by jensotto** [comment]
I'm not sure if it has anything to do with this directly, but at the same time when this error started we also saw that we got a lot of access denied errors in the event log and database server logs about a machine account for the server that ran the DSC script that tried to log into the SharePoint databases. I guess this is due to the ScriptsToProcess is run under the machine account.

Also this dependency on ReverseDSC creates an extra challenge when using Pull Server (Azure Automation Account). The modules in the Automation Account is automatically downloaded as part of executing the DSC script, but when an dependency exists on ReverseDSC which is not a DSC resource this module needs to be installed and in the future updated manually instead of relying on the automation provided in the Pull Server.

**Comment by jensotto** [comment]
I added a Write-Warning statement just before the lines I added, and I saw that the text was written during DSC configureation. Should that be sufficient?

**Comment by jensotto** [comment]
I tried a reboot too, and it still failed

**Comment by jensotto** [comment]
After thinking more about the issue regarding access denied when the computer account tries to log on to the database server, I realise that it will not be possible to have the ScriptsToProcess as it currently is implemented. It will then litter the logs with access denied errors. Maybe it's possible to detect if the script is run by the local configuration manager and skip loading the SP SnapIn. But that would still not fix the issue wit the Pull Server as I described earlier.

**Comment by ykuijs** [comment]
Can you try the lines with another resource, for example SPFarmAdministrators? On my end, this works perfectly with that resource. Will test with the SPFarm on my end as well.

Can you explain the other issues a little more? Not sure what you mean there.

**Comment by jensotto** [comment]
When the ScripsToProcess is executed during a configuration it's my understanding that this runs under the machine account. Because ScriptsToProcess includes a script that loads the SP SnapIn it will try to contact the SP database (configuration database) using the machine account. If this is true it will create unnecessary errors in logs as the machine account does not have access to do so. This is what we observed. I therefore believe that we can't ScriptsToProcess loading the SP SnapIn during DSC configuration.

**Comment by bartvermeersch** [comment]
Adding those lines to the SPFarm resource seem to work for me. CreateSPFarm now works and it stops at the next in line (SPManagedAccount).

**Comment by jensotto** [comment]
The Pull Server can be configured to host modules required by the DSC configurations. These can automatically be downloaded when LCM pulls a new configuration from the Pull Server. This only covers DSC resources used in a configuration. Since ReversedDSC is not a DSC resource and thus not used/referenced in the configuration it will never be downloaded automatically by the LCM. This means that ReverseDSC needs to be installed manually prior to execution of the configuration. This also is true when ReverseDSC is updated in the future and SharePointDSC takes a dependency on a newer version of ReverseDSC.
It just makes everything a bit more convoluted and not as elegant as it was prior to the ReverseDSC dependency.

**Comment by jensotto** [comment]
I've tested it in two different farms now, and I get the same error in both farms on multiple servers. I can't understand why it would work in some cases and not in others.

**Comment by ykuijs** [comment]
Exactly what are you doing? Have you added the lines at the top (on line 1) of the following file:
C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\4.5.0\DSCResources\MSFT_SPFarm\MSFT_SPFarm.psm1

**Comment by ykuijs** [comment]
I get what you mean with the Pull Server issue. That is an interesting scenario. Will look for a solution!

**Comment by jensotto** [comment]
I've modified the first few lines of MSFT_SPFarm.psm1:

```
$script:SPDscUtilModulePath = Join-Path -Path $PSScriptRoot -ChildPath '..\..\Modules\SharePointDsc.Util\SharePointDsc.Util.psm1'
Import-Module -Name $script:SPDscUtilModulePath

$script:resourceModulePath = Split-Path -Path (Split-Path -Path $PSScriptRoot -Parent) -Parent
$script:modulesFolderPath = Join-Path -Path $script:resourceModulePath -ChildPath 'Modules'

$script:resourceFarmHelperModulePath = Join-Path -Path $script:modulesFolderPath -ChildPath 'SharePointDsc.Farm'
Import-Module -Name (Join-Path -Path $script:resourceFarmHelperModulePath -ChildPath 'SPFarm.psm1')

function Get-TargetResource
{
```

The rest is unmodified from the released version of SharePointDSC v4.5.0

**Comment by ykuijs** [comment]
Just to be sure: You updated the file on the SharePoint server where you push the MOF file to, not on the server you generate the MOF file on (if this is a different server). Is this correct?

**Comment by jensotto** [comment]
Yes, I edit the module file on the SharePoint server that runs the configuration (MOF file). MOF files are generated using Azure Pipelines using an isolated build server. I have not made any modification to the module on that build server.

**Comment by ykuijs** [comment]
@jensotto and I found a solution and I am now creating a PR to resolve this solution.

**Comment by ykuijs** [comment]
PR merged, release process is running. v4.5.1 will be released tonight or tomorrow
