### ISSUE TITLE
MSFT_SPFarm: throws error for ApplicationCredentialKey when ReverseDSC SPFarm on SP2013 

### ISSUE THREAD

**Issue by bartvermeersch** [dsccommunity/SharePointDsc#1285]
#### Details of the scenario you tried and the problem that is occurring
Run SharePointDSC.Reverse.ps1 on a SP2013 farm for DSC farm-configuration:

```powershell
.\SharePointDSC.Reverse.ps1 -ComponentsToExtract @("SPFarm")
```
throws exception "Specifying ApplicationCredentialKey is only supported on SharePoint 2019"

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19913.amd64fre.winblue_ltsb_escrow.201207-1920
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used
Name          Version Path
----          ------- ----
SharePointDSC 4.5.0   C:\Users\username\Documents\WindowsPowerShell\Modules\SharePointDSC\4.5.0\SharePointDSC.psd1

**Comment by bartvermeersch** [comment]
I'm mixing versions which could explain my issue (SharePointDSC.Reverse v3.7.0.1 with SharePointDSC v4.5.0)

**Comment by ykuijs** [comment]
Hi @bartvermeersch, that could indeed be the issue. With the release of SharePointDsc v4.5, SharePointDsc.Reverse is no longer required 😉 Please remove that module and try again. Let me know if the issue still occurs afterwards!

**Comment by bartvermeersch** [comment]
It did solved the issue!
