### ISSUE TITLE
Extend MSFT_SPSecurityTokenServiceConfig

### ISSUE THREAD

**Issue by ThomasLie** [dsccommunity/SharePointDsc#1302]
### Description
Extend the resource to set the properties 'FormsTokenLifetime', 'WindowsTokenLifetime' and 'LogonTokenCacheExpirationWindow'
[MSFT_SPSecurityTokenServiceConfig.zip](https://github.com/dsccommunity/SharePointDsc/files/6235836/MSFT_SPSecurityTokenServiceConfig.zip)

### Proposed properties
FormsTokenLifetime
WindowsTokenLifetime
LogonTokenCacheExpirationWindow

**Comment by ykuijs** [comment]
@ThomasLie is working on implementing this enhancement.

**Comment by ykuijs** [comment]
Reopening because this hasn't been implemented yet.
