### ISSUE TITLE
SPFarmAdministrators: Resource fails with error message: An item with the same key has already been added

### ISSUE THREAD

**Issue by PwrKjll** [dsccommunity/SharePointDsc#1310]
Error Message: PowerShell DSC resource MSFT_SPFarmAdministrators failed to execute Set-TargetResource
functionality with error message: An item with the same key has already been added

Details of the scenario you tried and the problem that is occurring
Just added one AD-group to Members in resource SPFarmAdministrators

Verbose logs showing the problem
Suggested solution to the issue
Case insensitive search of groups and accounts before adding them to Lists and Dictionaries

The DSC configuration that is used to reproduce the issue (as detailed as possible)
PowerShell DSC:
```PowerShell
SPFarmAdministrators 'FarmAdministrators' {
    PsDscRunAsCredential = $SetupCredential
    IsSingleInstance = 'Yes'
    Members = @($ConfigurationData.NonNodeData.SharePoint.AdministratorsGroup) +
                        @($ConfigurationData.NonNodeData.SharePoint.MonitorsGroup) | ? { $_ }
    DependsOn = @('[SPFarm]Farm')
}
```
MOF:
```
instance of MSFT_SPFarmAdministrators as $MSFT_SPFarmAdministrators1ref
{
    ResourceID = "[SPFarmAdministrators]FarmAdministrators";
    PsDscRunAsCredential = $MSFT_Credential29ref;
    Members = {
        "\SpIntAdmins"
    };
    SourceInfo = "C:\Users\JhonDoe\repos\Source\DSC\~Config\SPFarmDSC.ps1::785::13::SPFarmAdministrators";
    IsSingleInstance = "Yes";
    ModuleName = "SharePointDsc";
    ModuleVersion = "4.6.0";

    DependsOn = {

        "[SPFarm]Farm"
    };
    ConfigurationName = "SPFarmDSC";
};
```

The operating system the target node is running
```
OsName : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture : 64-bit
WindowsBuildLabEx : 14393.3750.amd64fre.rs1_release.200601-1853
OsLanguage : en-US
OsMuiLanguages : {en-US}
```

Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

Version and build of PowerShell the target node is running
```Name Value

PSVersion 5.1.14393.3471
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14393.3471
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
```

Version of the DSC module that was used
ModuleVersion = "4.6.0";

**Comment by ykuijs** [comment]
Hi @PwrKjll, few questions:

1. Could you please share the Verbose logging? Run Start-DscConfiguration with the -Wait -Verbose options.
2. The MOF info you shared lists the "\SpIntAdmins" as the item to be configured. Could you please change this to a full domain\user format and try again?

**Comment by IlleNilsson** [comment]
I have this issue as well. I've tried using accounts and groups. All prefixed with domain as <domain>\<Account> with SharePoint 2016 on Windows Server 2012 R2 and SharePoint 2019 on Windows Server 2019. Here is my MOF. 

instance of MSFT_SPFarmAdministrators as $MSFT_SPFarmAdministrators1ref
{
ResourceID = "[SPFarmAdministrators]FarmAdministrators";
 PsDscRunAsCredential = $MSFT_Credential45ref;
 MembersToInclude = {
    "<Domain>\\<Group>"
};
 SourceInfo = "<Secret>";
 IsSingleInstance = "Yes";
 ModuleName = "SharePointDsc";
 ModuleVersion = "4.6.0";

DependsOn = {

    "[SPFarm]Farm"};

 ConfigurationName = "SPFarmDsc";

};

**Comment by ykuijs** [comment]
@IlleNilsson Can you share your verbose output as well? This makes searching for the line where it goes wrong (and therefore a potential reproduction on my end) much easier.

**Comment by IlleNilsson** [comment]
Shure, hang on, it will take an hour

**Comment by IlleNilsson** [comment]
It took more than an hour :)

VERBOSE: [SERVER]:                            [[SPFarm]Farm] Target Values: AdminContentDatabaseName=__FarmContent;
CentralAdministrationPort=5600; DatabaseServer=SHPCNT; Ensure=Present; FarmAccount=DOM\FarmAccount;
FarmConfigDatabaseName=__FarmConfig; IsSingleInstance=Yes; Passphrase=DOM\FarmAccount; RunCentralAdmin=True;
ServerRole=ApplicationWithSearch; Verbose=True
VERBOSE: [SERVER]:                            [[SPFarm]Farm] Test-TargetResource returned True
VERBOSE: [SERVER]: LCM:  [ End    Test     ]  [[SPFarm]Farm]  in 3.6370 seconds.
VERBOSE: [SERVER]: LCM:  [ Skip   Set      ]  [[SPFarm]Farm]
VERBOSE: [SERVER]: LCM:  [ End    Resource ]  [[SPFarm]Farm]
VERBOSE: [SERVER]: LCM:  [ Start  Resource ]  [[SPFarmAdministrators]FarmAdministrators]
VERBOSE: [SERVER]: LCM:  [ Start  Test     ]  [[SPFarmAdministrators]FarmAdministrators]
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Importing the module
MSFT_SPFarmAdministrators in force mode.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Importing the module
MSFT_SPFarmAdministrators in force mode.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Testing Farm Administrators
configuration
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Getting Farm Administrators
configuration
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Executing as the local run
as user DOM\dsc_engine
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Leaving BeginProcessing
Method of Get-SPWebApplication.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Leaving ProcessRecord Method
 of Get-SPWebApplication.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Leaving EndProcessing Method
 of Get-SPWebApplication.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Leaving BeginProcessing
Method of Get-SPWeb.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Leaving ProcessRecord Method
 of Get-SPWeb.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Leaving EndProcessing Method
 of Get-SPWeb.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Current Values:
IsSingleInstance=Yes; Members=(BUILTIN\administrators,DOM\FarmAccount,DOM\dsc_engine); MembersToExclude=;
MembersToInclude=(RD01\SpLabAdmins)
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Target Values:
IsSingleInstance=Yes; MembersToInclude=(RD01\SpLabAdmins); Verbose=True
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Processing MembersToInclude
parameter
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] RD01\SpLabAdmins is not a
Farm Administrator, but is included in MembersToInclude:
<DesiredValue>RD01\SpLabAdmins</DesiredValue>
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Test-TargetResource returned
 False
VERBOSE: [SERVER]: LCM:  [ End    Test     ]  [[SPFarmAdministrators]FarmAdministrators]  in 1.7350 seconds.
VERBOSE: [SERVER]: LCM:  [ Start  Set      ]  [[SPFarmAdministrators]FarmAdministrators]
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Importing the module
MSFT_SPFarmAdministrators in force mode.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Importing the module
MSFT_SPFarmAdministrators in force mode.
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Setting Farm Administrators
configuration
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Getting Farm Administrators
configuration
VERBOSE: [SERVER]:                            [[SPFarmAdministrators]FarmAdministrators] Executing as the local run
as user DOM\dsc_engine
VERBOSE: [SERVER]: LCM:  [ End    Set      ]  [[SPFarmAdministrators]FarmAdministrators]  in 0.3750 seconds.
PowerShell DSC resource MSFT_SPFarmAdministrators  failed to execute Set-TargetResource functionality with error
message: An item with the same key has already been added.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SERVER

**Comment by ykuijs** [comment]
The root cause of this issue is the SharePoint snap-in. Unlike modules, snap-ins cannot be loaded multiple times but also can't be used across scopes. So if you are in a different scope and check if the snap-in is loaded, the answer is no. If you then try to load the snap-in, the "An item with the same key has already been added." error is thrown :-(

The best was to resolve this is to convert the snap-in into a module, but that has to be done by the SharePoint Product Group since that is outside our control.

@IlleNilsson I am trying to reproduce the issue, but am unable to. I am using the newest release v4.7. Can you validate that the issue occurs in that version as well?

Also: Can you please share as much information as possible of your setup that can be relevant, which I can then use to reproduce the issue?

**Comment by IlleNilsson** [comment]
Hi, I have left my SharePoint assignment. So @Kjell ***@***.***>, you will have to pick this up. I can be of assistance, but not leading.
________________________________

**Comment by IlleNilsson** [comment]
Hi, I've just tried it with version 4.7.0 and the problem remains.

**Comment by luigilink** [comment]
Hi, I have also the same problem with the 4.5.0 so I stay in 4.4.0 :(

**Comment by ykuijs** [comment]
Hi @luigilink, that is correct. With the addition of native ReverseDsc support we made an update to load the snapin a certain way. We needed that to prevent the exact same error to be thrown during a config export.

It now looks like that because of this we are hitting the same issue in these situations. Before I was unable to replicate, but yesterday I have been working on a new resource which I just started testing. During these tests I am hitting the same issue. I have a clue where this is coming from, now just figuring out how to solve it.

Will keep all of you posted!

**Comment by ykuijs** [comment]
Of course: If anyone has an idea on how to fix this issue, I am always open to suggestions 😉

**Comment by luigilink** [comment]
Any updates of this issue ?

**Comment by luigilink** [comment]
I saw that the PSSnapin can be called three times and not exactly with the same code:

- SharePointDsc.Util.psm1:

        if (`$null -eq (Get-PSSnapin -Name Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue))
        {
            Add-PSSnapin Microsoft.SharePoint.PowerShell
        }

- Import-SPPowerShellSnapIn.ps1

if (-not (Get-PSSnapin Microsoft.SharePoint.Powershell -ErrorAction SilentlyContinue))
{
    Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue
}

- MSFT_SPSite.psm1:

 $newSPSiteCmd = "Add-PSSnapin Microsoft.SharePoint.PowerShell;"

**Comment by ykuijs** [comment]
Hi @luigilink, the issue here is that SharePoint is still using snapins (to be changed in SharePoint Server Subscription Edition!!!).

So far I do not have a solution yet, but might have an idea how to resolve this issue. Have to find some time to test if this will work.

The workaround you are describing will work

**Comment by ykuijs** [comment]
Hi @luigilink, do you have the possibility to test the following update:
Replace the content in Import-SPPowerShellSnapIn.ps1 file with the following code and reproduce the issue
```PowerShell
$stack = Get-PSCallStack

if ($stack[1].Position.Text -eq 'Export-SPConfiguration')
{
    if (-not (Get-PSSnapin Microsoft.SharePoint.Powershell -ErrorAction SilentlyContinue))
    {
        Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue
    }
}

```

**Comment by ykuijs** [comment]
Hi @luigilink, could you please test the above change in combination with the following change:
Remove (or comment out) the first two lines from the file DSCResources\MSFT_SPFarmAdministrators\MSFT_SPFarmAdministrators.psm1 and then try running your configuration again?

**Comment by luigilink** [comment]
Hi @ykuijs for this long silence; I will check today and share my result with the $stack variable in Import-SPPowerShellSnapIn.ps1

**Comment by luigilink** [comment]
So two things, firtsly this $stack variable in Import-SPPowerShellSnapIn.ps1 doesn't change anything on the issue, I have still "An item with the same key has already been added".

Secondly I tried something tell me if you can implement this:
It seems that these two lines are responsible of the error: 
$script:SPDscUtilModulePath = Join-Path -Path $PSScriptRoot -ChildPath '..\..\Modules\SharePointDsc.Util'
Import-Module -Name $script:SPDscUtilModulePath

The SharePointDsc.Util module is already loaded from the SharePointDsc.psd1 file at the line 71:
NestedModules        = @("Modules\SharePointDsc.Util\SharePointDsc.Util.psd1")

I removed these two lines on each resource files and no more issue during the full deployement of a SharePoint Farm.

@ykuijs what do you think ?

**Comment by ykuijs** [comment]
It is a combination of both changes that does the trick. The Import-SPPoweShellSnapIn.ps1 is required for the ReverseDsc integration, but in some cases that also threw the same error. That is why we added the two lines at the top of each resource.

As it turns out, here there are also scenarios where the error is thrown as you encountered.

By implemented both changes, we make sure the snap-in is only loaded when the Export cmdlet is called.

I will include these fixes in my next Bugfix PR!
