### ISSUE TITLE
SPContentDatabase: trailing / in Webappurl is not removed

### ISSUE THREAD

**Issue by bartvermeersch** [dsccommunity/SharePointDsc#1317]
#### Details of the scenario you tried and the problem that is occurring
Testing for an exsiting SPContentDatabase fails when 
- it contains a trailing /
- it contains upper case characters

#### Verbose logs showing the problem
    <ConfigurationDrift Source="MSFT_SPContentDatabase">
        <ParametersNotInDesiredState>
            <Param Name="WebAppUrl"><CurrentValue>https://test.domain.com</CurrentValue><DesiredValue>https://test.domain.com/</DesiredValue></Param>
        </ParametersNotInDesiredState>
    </ConfigurationDrift>

AND

    <ConfigurationDrift Source="MSFT_SPContentDatabase">
        <ParametersNotInDesiredState>
            <Param Name="WebAppUrl"><CurrentValue>https://test.domain.com</CurrentValue><DesiredValue>https://TEST.domain.com</DesiredValue></Param>
        </ParametersNotInDesiredState>
    </ConfigurationDrift>

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        $Prefix = "TEST"
        SPContentDatabase CDB_Projects_0001
        {
            DatabaseServer       = $ConfigurationData.NonNodeData.DatabaseServer;
            Enabled              = $True;
            Ensure               = "Present";
            WarningSiteCount     = 280;
            MaximumSiteCount     = 300;
            Name                 = $Prefix + "_CDB_Projects_0001";
            PsDscRunAsCredential = $SPSetupAccount
            WebAppUrl            = "https://" + $Prefix +".domain.com/"
        }```

#### The operating system the target node is running

#### Version and build of PowerShell the target node is running

#### Version of the DSC module that was used
4.5.1

**Comment by bartvermeersch** [comment]
You can ignore the case sensitivity, that seems to be ok. It is only the trailing "/" which results in an undesired state.

**Comment by ykuijs** [comment]
Hi @bartvermeersch I will check if I can reproduce and fix the issue

**Comment by ykuijs** [comment]
Hi @bartvermeersch, I was able to reproduce the issue and now am going to implement a fix. This will be included in my next Bugfix PR.

**Comment by bartvermeersch** [comment]
Perfect, thank you @ykuijs !
