### ISSUE TITLE
Why is parameter SkipRegisterAsDistributedCacheHost of Connect-SPConfigurationDatabase hardcoded to true?

### ISSUE THREAD

**Issue by Yvand** [dsccommunity/SharePointDsc#1321]
In [MSFT_SPFarm.psm1#L831](https://github.com/dsccommunity/SharePointDsc/blob/852a3779db1166cb5412451a3463992b4efa59f1/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L831), parameter SkipRegisterAsDistributedCacheHost of Connect-SPConfigurationDatabase is hardcoded to true:

```powershell
$executeArgs = @{
	DatabaseServer                     = $params.DatabaseServer
	DatabaseName                       = $params.FarmConfigDatabaseName
	Passphrase                         = $params.Passphrase.Password
	SkipRegisterAsDistributedCacheHost = $true
}
```

It seems to me that it should be a parameter settable in the DSC script, as its [default behavior](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/connect-spconfigurationdatabase?view=sharepoint-ps) is $false, and may avoid the need to run SPDistributedCacheService later (which is especially slow).
Is there some reason I'm missing?

**Comment by ykuijs** [comment]
This is in the resource for years, so not sure why that decision was made. My guess is that it was so that you don't have to unprovision the DC later on.

It makes sense to add a parameter to the resource and have the default value of that resource be $false. That way you can specify true if there is a need in your config.

**Comment by Yvand** [comment]
Thank you for your input. Yes I strongly believe this should be done because:

- It's the default behavior of SharePoint configuration wizard.
- Resource SPDistributedCacheService takes a very significant time to run (between 5 to 6 mins) and this will allow people to get rid of it for most scenarios
- The only reason left to run resource SPDistributedCacheService is to enable firewall rules, but I looked at the code and it's just plain (non-SharePoint) PowerShell, so for my script I will do that in a xScript

I will submit a PR asap to allow setting parameter SkipRegisterAsDistributedCacheHost in SPFarm resource

**Comment by Yvand** [comment]
@ykuijs what should be the default value of parameter SkipRegisterAsDistributedCacheHost in resource SPFarm?

- If $true: current value of SharePointDsc for years (maybe forever)
- If $false: Default value of [cmdlet Connect-SPConfigurationDatabase](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/connect-spconfigurationdatabase?view=sharepoint-ps)

I think it should be $false, because by default SharePointDsc resources should behave like the SharePoint API, unless there is a good reason not to, which I don't really see here.
