### ISSUE TITLE
MSFT_SPSearchTopology - Fails if not executed on server with index role

### ISSUE THREAD

**Issue by ThomasLie** [dsccommunity/SharePointDsc#1322]
#### Details of the scenario you tried and the problem that is occurring
Creating a search topology fails when trying to create an index partition on a server which does not have the index role.

#### Verbose logs showing the problem
DSC resource MSFT_SPSearchTopology failed to execute Set-TargetResource functionality with error message:
Cannot bind parametet 'RootDirectory' to the target. Exception setting "RootDirectory". Could not find part of the path "G:\SEARCHINDEX\0".

#### Suggested solution to the issue
Create the root directory using DSC File resource, create file share and use share path for the property 'RootDirectory' just before crreating the search topology.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Search = @{
    Provision                    = $true
       Publish                    = $true
    Name                         = "Search Service Application"
       ApplicationPoolName = "SharePoint Search Applications"
    DatabaseName           = "SEARCH_DB_001"
       DatabaseServer          = "SEARCH_DB_SERVER"
       CloudSSA                   = $false
    SearchCenterUrl       = https://sharepoint.contoso.com/search
    SearchTopology        = @{
        Admin                           = @("Server1","Server2")
        Crawler                  = @("Server1","Server2")
        ContentProcessing = @("Server2","Server2")
        AnalyticsProcessing = @("Server2","Server2")
        QueryProcessing   = @("Server1","Server2")
    }
    SearchIndexes = @(
        @{
            Servers              = @("Server3","Server4")
            Index                = 0
            RootDirectory = "G:\SEARCHINDEX\0"
        }
} 
```

#### The operating system the target node is running
OS: Windows Server 2019 EN-US
#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used
4.2.0

**Comment by ykuijs** [comment]
This was a [known issue in SP2013](https://support.microsoft.com/en-us/office/sharepoint-server-2013-known-issues-780242a6-236e-4d7a-8379-118a1aaa2a51) (look for 'New-SPEnterpriseSearchIndexComponent checks the existence of RootDirectory in the wrong server').

This resource already resolved this for SP2013, but uses the regular cmdlet for SP2016+. Just tested this in SP2019 and the issue occurs there as well. Just included SP2016/2019 in the specified workaround. Will be included in my next Bugfix PR.
