### ISSUE TITLE
Support for SharePoint Server Subscription Edition

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/SharePointDsc#1339]
Any plans of implementing support for the newest SharePoint version? I would like to contribute if needed!

**Comment by shurick81** [comment]
Download page: https://www.microsoft.com/en-us/download/details.aspx?id=103322
English version file link: https://download.microsoft.com/download/9/0/4/90400fcd-2d16-4865-afd3-f301aa88fdf5/OfficeServer_en-us.iso

**Comment by andikrueger** [comment]
You can use the current version of SharePointDSC with SharePoint Server Subscription Edition already. It works fairly good so far.

If you like to test the preview of SharePointDSC V5 you can download it here: https://techcommunity.microsoft.com/t5/sharepointdsc/preview-release-with-support-for-sharepoint-server-subscription/ba-p/2579947

**Comment by ykuijs** [comment]
As Andi mentioned, we have a preview version available for SPSE. More information can be found in the mentioned blog post. Please report back any issues by creating an issue here.

Closing the issue now.

**Comment by shurick81** [comment]
Just a minor thing probably: updating wiki so that it says about Subscription Edition https://github.com/dsccommunity/SharePointDsc/wiki

**Comment by ykuijs** [comment]
Wiki updated! Thanks for noticing this!
