### ISSUE TITLE
Problem with version 5.0 of resource MSFT_SPWebApplication.psm1

### ISSUE THREAD

**Issue by breivald** [dsccommunity/SharePointDsc#1365]
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE: MSFT_SPWebApplication.psm1: hardcoded url for WA
   
    ISSUE DESCRIPTION (this template):
    I get an error when configurring a farm that it can't find web application on url https://root.portal.politie.local
    I searched the code and found this on line 110 in MSFT_SPWebApplication.psm1
    $wa = Get-SPWebApplication https://root.portal.politie.local
    I have some other issues when running the script but hard to say if this one is the root cause

#### Verbose logs showing the problem

Cannot find an SPWebApplication object with Name, Id, or Url: https://root.portal.politie.local.
    + CategoryInfo          : InvalidData: (Microsoft.Share...tWebApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SpCmdletGetWebApplication
    + PSComputerName        : swazserver00.c0nt0s00.local

#### Version of the DSC module that was used
Version 5.0

**Comment by ykuijs** [comment]
@breivald This is correct, my apologies!

I am working on a PR that is correcting this. Thanks for reporting!

**Comment by ykuijs** [comment]
Closed via #1362
