### ISSUE TITLE
SPWebAppPolicy: arry of Members delimited with "," or not?

### ISSUE THREAD

**Issue by bartvermeersch** [dsccommunity/SharePointDsc#1375]
Tested on PS5.1 with SharePointDSC v5.0.0

The list of Members in an SPWebAppPolicy throws an error when it is delimited with an "," while ReverseDSC does put an "," delimiter between the Members. Either reverseDSC or DSC contains a bug.

Output from ReverseDSC:

        SPWebAppPolicy 053f1e72-e106-0000-0000-5783a3759000
        {
            Members                = @(
                MSFT_SPWebPolicyPermissions {
                    Username = $xx.UserName
                    IdentityType = 'Native'
                    PermissionLevel = 'Full Read'
                    ActAsSystemAccount = $False
                },
                MSFT_SPWebPolicyPermissions {
                    Username =  $xx.UserName
                    IdentityType = 'Claims'
                    PermissionLevel = 'Full Read'
                    ActAsSystemAccount = $False
                },
                MSFT_SPWebPolicyPermissions {
                    Username =  $xx.UserName
                    IdentityType = 'Claims'
                    PermissionLevel = 'Full Read'
                    ActAsSystemAccount = $False
                });
            PsDscRunAsCredential   = $xx;
            SetCacheAccountsPolicy = $False;
            WebAppUrl              = "https://xx/";
        }

This throws an error because of the "," delimiter, removing the "," solves the issue:

SPWebAppPolicy WebAppPolicy
        {
            WebAppUrl            = "http://sharepoint.contoso.com"
            Members              = @(
                MSFT_SPWebPolicyPermissions {
                    Username           = "contoso\user1"
                    PermissionLevel    = "Full Control"
                    ActAsSystemAccount = $true
**==>**         },
                MSFT_SPWebPolicyPermissions {
                    Username        = "contoso\Group 1"
                    PermissionLevel = "Full Read"
                    IdentityType    = "Claims"
                }
            )
            PsDscRunAsCredential = $SetupAccount
        }

**The error:**
At line:1295 char:19
+ },
+ ~
Missing expression after unary operator ','. At line:1296 char:17
+ MSFT_SPWebPolicyPermissions {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'MSFT_SPWebPolicyPermissions' in expression or statement.

**Comment by ykuijs** [comment]
Have tracked this issue back to an issue in ReverseDsc. Am working on fixing that, before I can update the required version in SPDsc.

**Comment by ykuijs** [comment]
Fixed in [ReverseDsc v2.0.0.10](https://www.powershellgallery.com/packages/ReverseDSC/2.0.0.10) via PR [microsoft/ReverseDSC#25].

Working on the PR for SPDsc to use this version now.
