### ISSUE TITLE
MSFT_SPSearchIndexPartition: ReverseDSC returns list of strings for RootDirectory 

### ISSUE THREAD

**Issue by bartvermeersch** [dsccommunity/SharePointDsc#1376]
Tested on SP5.1 and SharePointDSC v5.0.0

ReverseDSC returned a list of strings for RootDirectory in SPSearchIndexPartition

ReverseDSC returned this config:
        SPSearchIndexPartition 5531c30e-28a4-404a-9f56-d5b3af242c8f
        {
            Index                = 0;
            PsDscRunAsCredential = $xx;
            RootDirectory        = @("E:\SearchIndex\0","E:\SearchIndex\0","E:\SearchIndex\0");
            Servers              = "$ConfigurationData.NonNodeData.SearchIndexPartitionServers";
            ServiceAppName       = "Search Service Application";
        }

Yes it contained three identical strings as RootDirectory.
While RootDirectory should be a string instead of an array.

**Comment by bartvermeersch** [comment]
Thanks Yorick, (I've changed the if statement to have some output):
![image](https://user-images.githubusercontent.com/1407940/153409449-78a430d9-0854-40a3-be5f-155f4e022be0.png)

**Comment by ykuijs** [comment]
Interesting output, that explains why there is an array in the output. Can you share the output of the $searchComponent variable?

**Comment by bartvermeersch** [comment]
![image](https://user-images.githubusercontent.com/1407940/154075905-9c2e93b7-cf6c-437b-8c5f-a702e284679f.png)

**Comment by ykuijs** [comment]
Got it! The Index Partition has three index components, which the code does not handle properly. So it returns the RootDirectory of all three components instead of just one.

I will implement a fix for this issue.

**Comment by ykuijs** [comment]
The fi
