### ISSUE TITLE
SPTimerJobState: Can't find Resource with Invoke

### ISSUE THREAD

**Issue by Mettcon** [dsccommunity/SharePointDsc#1378]
#### Details of the scenario you tried and the problem that is occurring
 ```powershell
$prop = @{
             TypeName             = 'some.Path.PdfExportWorkItemJob'
             WebAppUrl            = 'some Url'
             Enabled              = $true
             Schedule             = 'weekly at sat 7:00'
             PsDscRunAsCredential = $SetupAccount
}
PS > $SetupAccount = Get-Credential 
PS > Invoke-DscResource -Name SPTimerJobState -Method test -Property $prop -ModuleName SharePointDsc
```
throws  

    Invoke-DscResource : Resource SPTimerJobState was not found.
#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.447.amd64fre.rs1_release_inmarket.161102-0100
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used
Name          Version Path
----          ------- ----
SharePointDSC 5.1.0   C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\5.1.0\SharePointDSC.psd1
SharePointDSC 5.0.0   C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\5.0.0\SharePointDSC.psd1
SharePointDSC 4.3.0   C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\4.3.0\SharePointDSC.psd1

**Comment by ykuijs** [comment]
Or use this command instead:
```
$SetupAccount = Get-Credential 
$prop = @{
            TypeName             = 'some.Path.PdfExportWorkItemJob'
            WebAppUrl            = 'some Url'
            Enabled              = $true
            Schedule             = 'weekly at sat 7:00'
            PsDscRunAsCredential = $SetupAccount
}
Invoke-DscResource -Name SPTimerJobState -Method test -Property $prop -ModuleName @{ ModuleName = "SharePointDsc"; ModuleVersion = '5.0.0' }
```

**Comment by Mettcon** [comment]
Specify the ModuleVersion helped. 
thx a lot

**Comment by ykuijs** [comment]
Good to hear! Let us know when you have any other questions or ideas for improvements to SharePointDsc!
