### ISSUE TITLE
[SPSearchIndexPartition] RootDirectory needs to exist on the server that is executing this resource

### ISSUE THREAD

**Issue by ChristophHannappel** [dsccommunity/SharePointDsc#1384]
Hi,

the Ressource `SPSearchIndexPartition` requires to have the driveletter available on the host where it is executed even if it does not host the Index Partition.
The creation of the first Index Partition via `SPSearchTopology` doesn't require the drive letter to be available. 
Is there a technical reason why `SPSearchIndexPartition` checks the Path and `SPSearchTopology` does not?

Would it be possible to add a parameter to skip this test on the ressource?

**Comment by ykuijs** [comment]
This is due to an issue with the `New-SPEnterpriseSearchIndexComponent` cmdlet. If the specified path doesn't exist locally, the cmdlet will fail. This was a known issue in SP2013, which was not resolved in later versions.

This was discussed in and implemented as a result of issue #1322.

So therefore it is unfortunately not possible to add the parameter.

**Comment by andikrueger** [comment]
This page lists the basics concepts of SharePointDSC Resources: https://github.com/dsccommunity/SharePointDsc/wiki/Understanding-Resources

**Comment by ykuijs** [comment]
The Readme.md file (and therefore also the Wiki) contains a note with this exact information:
> NOTE 1: To make sure that the search topology is applied correctly, the path specified for RootDirectory needs to exist on the server that is executing this resource. For example, if the below example was executed on "Server1" it would also need to ensure that it was able to create the index path at I:. If no disk labeled I: was available on server1, this would fail, even though it will not hold an actual index component.

https://github.com/dsccommunity/SharePointDsc/wiki/SPSearchIndexPartition

What I have done in a config is to create the farm on a SP backend server and then have a search server wait until the farm has been created before joining the farm and creating the Search service app and topology. I am working on a PR to add this template config as an example to this repository.

**Comment by ykuijs** [comment]
I have just merged the PR, you can find the example here:
https://github.com/dsccommunity/SharePointDsc/blob/4c78a21ad1eaf5dfcf9484fd9e4a669f7fc5e51f/SharePointDsc/FarmDeployment/Deploy_SharePoint.ps1#L1292-L1341

It is does not directly contain the SPSearchIndexPartition resource, but does have the described mechanism.

**Comment by ChristophHannappel** [comment]
@ykuijs  Thank you for the example
