### ISSUE TITLE
SPDistributedCacheClientSetting: Missing SP2019 and SE Values

### ISSUE THREAD

**Issue by ChristophHannappel** [dsccommunity/SharePointDsc#1399]
### Problem description

The Ressource is missing the SP2019 and SPSE specific container Settings:
* DistributedDbLevelFailoverCache
* DistributedEdgeHeaderCache
* DistributedFileStorePerformanceTraceCache
* DistributedSPAbsBlobCache
* DistributedSPCertificateValidatorCache
* DistributedSPOAuthTokenCache
* DistributedStopgapCache
* DistributedStopgapCache

They are documented at [SharePoint Server Subscription Edition and SharePoint Server 2019 PowerShell script](https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service?tabs=SCS1%2CSCS2%2CSCS3%2CSCS%2CSCS4#fine-tune-the-distributed-cache-service-by-using-a-powershell-script)

I'm happy to create a pull request, after I've done my other tasks :)

### Verbose logs

```text
N/A
```

### DSC configuration

```powershell
N/A
```

### Suggested solution

Add the SP2019/SE specific Container like it has been done with SP2016

### SharePoint version and build

```text
N/A
```

### Operating system the target node is running

```text
N/A
```

### PowerShell version and build the target node is running

```text
N/A
```

### SharePointDsc version

```text
5.1.0
```

**Comment by ykuijs** [comment]
Perfect, it is all yours! Just two comments:
- You are mentioning DistributedStopgapCache twice
- Settings DistributedUnifiedAppsCache and DistributedUnifiedAuditCache are missing from the above list, but are listed in the article

**Comment by ykuijs** [comment]
Hi @ChristophHannappel, any idea when you are able to fix this issue?

**Comment by ChristophHannappel** [comment]
Hi @ykuijs since its mostly copy and paste ill think i can create a pull request until 20. May.

**Comment by ChristophHannappel** [comment]
For documentation purposes - i've compared the valid values for the `ContainerType` Parameter of the `Get-SPDistributedCacheClientSetting` between SharePoint Server 2016, 2019 and Subscription Edition.
The new Cache Container are:
* DistributedClientSideAppUpdateTimeCache
* DistributedDbLevelFailoverCache
* DistributedEdgeHeaderCache
* DistributedFileStorePerformanceTraceCache
* DistributedSPAbsBlobCache
* DistributedSPCertificateValidatorCache
* DistributedSPOAuthTokenCache
* DistributedStopgapCache
* DistributedUnifiedAppsCache
* DistributedUnifiedAuditCache

**Comment by ChristophHannappel** [comment]
Also the Script example uses the variable `DHSC` twice. First for `DistributedHealthScoreCache` than later again for `DistributedUnifiedAuditCache`  - which seems like a copy and paste error
```PowerShell
#DistributedUnifiedAuditCache
$DHSC = Get-SPDistributedCacheClientSetting -ContainerType DistributedUnifiedAuditCache
$DHSC.MaxConnectionsToServer = 1
$DHSC.requestTimeout = "3000"
$DHSC.channelOpenTimeOut = "3000"
Set-SPDistributedCacheClientSetting -ContainerType DistributedUnifiedAuditCache $DHSC
```

Based on the naming scheme my proposal is `DUAuC` for `DistributedUnifiedAuditCache ` since `DUAC` is already used for `DistributedUnifiedAppsCache`
