### ISSUE TITLE
SiteDataServers property of the web application is not configurable

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/SharePointDsc#562]
It would be great if this property was configurable via DSC.
It's quite useful for optimizing search topology and performance.

Here is more details:
https://technet.microsoft.com/en-us/library/dn535606.aspx#BKMK_ReduceEffect
https://technet.microsoft.com/en-us/library/dd335962(v=office.14).aspx

**Comment by NikCharlebois** [comment]
@ykuijs I am working on adding this to the SPWebAppGeneralSettings resource

**Comment by ykuijs** [comment]
@NikCharlebois All yours!

**Comment by ykuijs** [comment]
@NikCharlebois Has this been implemented?

**Comment by paololec** [comment]
Please also add "ShowStartASiteMenuItem" (true/false) into SPWebAppGeneralSettings if possible.

**Comment by ykuijs** [comment]
@NikCharlebois Do you have this work still available somewhere? So I use your work to fix this issue.

**Comment by NikCharlebois** [comment]
@ykuijs I am afraid I never got to it.

**Comment by ykuijs** [comment]
Closed via #1359
