### ISSUE TITLE
SPInstallPrereqs: Microsoft Visual C++ 2017 x64 Additional Runtime wrong check for SP2019

### ISSUE THREAD

**Issue by paoIpao** [dsccommunity/SharePointDsc#908]
#### Details of the scenario you tried and the problem that is occurring
SPInstallPrereqs for SP2019 check test search for:
Microsoft Visual C++ 2017 x64 Additional Runtime - 14.14.*
and it return false because the installed version is Microsoft Visual C++ 2017 x64 Additional Runtime - 14.13.26020 

#### Suggested solution to the issue
Please check for "Microsoft Visual C++ 2017 x64 Additional Runtime - 14.*" and not "Microsoft Visual C++ 2017 x64 Additional Runtime - 14.14.*"

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
 SPInstallPrereqs SPPrereqs
        {            
            IsSingleInstance = "Yes"
            InstallerPath        = $SharePointBinaryPath + "\prerequisiteinstaller.exe"
            OnlineMode           = $true
                    Ensure               = "Present"
            PsDscRunAsCredential = $Credssp_admin
        }
```

#### The operating system the target node is running
Microsoft Windows Server 2016 Datacenter

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019
#### Version and build of PowerShell the target node is running

Name                           Value                                                                                                                                                           
----                           -----                                                                                                                                                           
PSVersion                      5.1.14393.2430                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                         
BuildVersion                   10.0.14393.2430                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                             
SerializationVersion           1.1.0.1  

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.0

**Comment by ykuijs** [comment]
We have detected this issue as well and are working on fixing this
