### ISSUE TITLE
New resource or parameter for finer search components tuning: temp directory

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/SharePointDsc#962]
### Description
In order to meet enterprise requirements, would not it be good to be able to move temp search files to the data disk, like in this artile: https://social.msdn.microsoft.com/Forums/office/en-US/5c4b664b-0e0c-44f4-9534-21123349c3e0/how-to-move-sharepoint-search-temp-location?forum=sharepointdevelopment

### Proposed properties
It can be something like this:

```PowerShell
SPSearchComponentPaths DataDrive
{
 ApplicationPath = "D:\SPSearchTemp"
 DefaultProjectPath = "D:\SPSearchTemp"
 GathererDataPath = "D:\SPSearchTemp"
 WorkingDirectory = "D:\SPSearchTemp"
 DependsOn            = "[SPSearchTopology]SearchTopology"
}
```
### Special considerations or limitations
none

**Comment by shurick81** [comment]
"According to Anthony Casillas, a Sr. Escalation Engineer for Microsoft, you can perform the following tasks to change the search temp location, referenced in the comments here. He also mentioned that this way is supported." https://blogs.technet.microsoft.com/searchguys/2012/09/18/managing-the-sp-gatherers-temp-files/

**Comment by ykuijs** [comment]
The new SPSearchSettings resource sounds like the perfect place for these settings.

Unfortunately the blog post is no longer available. Does one of you have a copy of what was in there?

**Comment by ykuijs** [comment]
Post is available again. Capturing solution here:

> I know this post is fairly old and the last comments were months ago, but I wanted to input for any future reference.
> 
> I work on the Search Team for Microsoft SharePoint and there is a way to alter this path, that is supported. I recently had a conversation with someone I know within the Product Team and confirmed we can use this method.
> 
> First is a quick high level flow of what happens at crawl time:
> 
> 1. As the mssdmn.exe (gatherer) goes out and fetches content, it will store the data in the TempPath defined at this registry key:
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\MicrosoftOffice Server\15.0\Search\Global\Gathering Manager\TempPath
> 
> 2. The mssearch.exe process will then perform a windows operation to RenameMove the file to the path defined here at this registry key:
> 
> ( Your "guid-crawl-x " will differ )
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\MicrosoftOffice Server\15.0\SearchComponents\52ccea97-e96c-47ca-bcc4-737823da6e85-crawl-0GathererDataPath
> 
> 3. Once the Content Processing Component Processes this data, the mssearch should then delete the file from this path.
> 
> We often times see customers install the SearchMS Office Server data on a drive that has inadequate space and we used to not have an easier way to move the path that the mssearchmssdmn temp stores its data to. here is the method to change that path now..
> 
> • $ssa.TempPath cmdlet has been removed 
> • To modify application path where mssdmnmssearch writes to, the following registry keys should be modified:
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\MicrosoftOffice Server\15.0\Search\Global\Gathering Manager\DefaultApplicationPath
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\MicrosoftOffice Server\15.0\SearchComponents\{Both admin and crawl components}\LocalStoragePath
> 
> • After that search service should be restarted 
> • and original folders:
> 
> C:\Program Files\Microsoft Office Servers\Debug\15.0\Data\Office Server\Applications\{both admin and crawl components}
> 
> • should be removed
> • ONLY modify these keys and on the Crawl Servers and Admin components..

**Comment by ykuijs** [comment]
Original blogpost

> While the SharePoint Gatherer is processing files (Office documents, PDFs, etc), it will store them temporarily on local disk.  By default this is in the Temp folder of the user running the OSearch14 service.  It'll look something like:
> 
> C:\Users\SHAREP~1\AppData\Local\Temp\gthrsvc_OSearch14
> 
> And during a large crawl, this directory can at times get quite large.  (as I found out today when a dev server started complaining abou the C drive being full)
> 
> Moving it is easy enough and there are 2 ways.
> 
> First, update the service application:
> 
> $searchapp= Get-SPEnterpriseSearchServiceApplication -identity "FAST Content SSA"
> $searchapp.TempPath = "D:\SearchTemp"
> 
> Note that setting the path takes effect immediately.  No need to call the $searchapp.Update() method.
> 
> UPDATE 5/17/2013
> If you use the SSA.TempPath approach and have multiple crawlers, you need to make sure to run the command on each server anyway.
> 
> Second approach is to update the registry directly:
> 
> $gmpath = 'HKLM:\Software\Microsoft\Office Server\14.0\Search\Global\Gathering Manager'
> Set-ItemProperty -Path $gmpath -Name UseSystemTemp -Value 0
> Set-ItemProperty -Path $gmpath -Name TempPath -Value "D:\SearchTemp"
> Restart-Service OSearch14
> 
> And don't forget to exclude the new temp folder from any AV scans.

**Comment by shurick81** [comment]
Hi, it's been a while. i wonder if it is something done already or is it something that community can help with?

**Comment by ykuijs** [comment]
Am investigating this topic and checking with some colleagues. There is no formal statement that this method is supported, so possibly it isn't a good idea (from a supportability perspective) to implement this issue.

**Comment by shurick81** [comment]
So you think this method is not really fully supported by Microsoft?

**Comment by ykuijs** [comment]
If the method isn't officially documented, it is a risk to use the method. 

I would recommend to raise an advisory case to get a formal supportability statement and ask what the supported method is to change the crawler temp directory.

**Comment by ykuijs** [comment]
Got some more replies from support engineers. They all say doing this is not recommended. The way to do this is to reinstall SharePoint and make sure it is installed on the correct drive.

This implementing this can result in supportability issues, I am going to close this issue.
